from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts import worktree_doctor_lib as lib  # noqa: E402


def _git(*args: str, cwd: Path) -> None:
    subprocess.run(["git", *args], cwd=cwd, check=True, capture_output=True, text=True)


def _make_git_worktree(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    _git("init", "--initial-branch=main", cwd=repo)
    _git("config", "user.email", "wt-test@example.com", cwd=repo)
    _git("config", "user.name", "Worktree Test", cwd=repo)
    (repo / "README.md").write_text("seed\n", encoding="utf-8")
    _git("add", "README.md", cwd=repo)
    _git("commit", "-m", "seed", cwd=repo)
    return repo


def _write_manifest(repo: Path, body: str) -> None:
    (repo / ".agents").mkdir(exist_ok=True)
    (repo / ".agents" / "worktree-adapter.yaml").write_text(body, encoding="utf-8")


def test_doctor_no_manifest_passes_canonical_only(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    payload = lib.run_doctor(repo)
    assert payload["status"] == "pass"
    assert payload["manifest"]["found"] is False
    ids = {check["id"]: check["status"] for check in payload["checks"]}
    assert ids["git_common_dir"] == "pass"
    assert ids["hooks_path"] == "skipped"
    assert ids["lefthook_shim"] == "skipped"
    assert ids["husky_dir"] == "skipped"


def test_doctor_lefthook_shim_missing_node_modules_fails(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    repo = _make_git_worktree(tmp_path)
    hooks_dir = repo / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    shim = hooks_dir / "pre-commit"
    shim.write_text(
        "#!/bin/sh\n"
        '# Code generated by lefthook. DO NOT EDIT.\n'
        'exec ./node_modules/lefthook-linux-x64/bin/lefthook run pre-commit "$@"\n',
        encoding="utf-8",
    )
    shim.chmod(0o755)
    isolated_path = str(Path(sys.executable).resolve().parent) + os.pathsep + "/usr/bin" + os.pathsep + "/bin"
    monkeypatch.setenv("PATH", isolated_path)
    payload = lib.run_doctor(repo)
    assert payload["status"] == "fail"
    lefthook = next(check for check in payload["checks"] if check["id"] == "lefthook_shim")
    assert lefthook["status"] == "fail"
    assert "charness worktree prepare" in (lefthook["next_action"] or "")


def test_doctor_lefthook_shim_resolves_via_node_modules(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    hooks_dir = repo / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    shim = hooks_dir / "pre-commit"
    shim.write_text("#!/bin/sh\nexec lefthook run pre-commit\n", encoding="utf-8")
    shim.chmod(0o755)
    binary_dir = repo / "node_modules" / "lefthook-linux-x64" / "bin"
    binary_dir.mkdir(parents=True)
    binary = binary_dir / "lefthook"
    binary.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    binary.chmod(0o755)
    payload = lib.run_doctor(repo)
    lefthook = next(check for check in payload["checks"] if check["id"] == "lefthook_shim")
    assert lefthook["status"] == "pass"
    assert payload["status"] == "pass"


def test_doctor_husky_marker_missing_fails(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    _git("config", "core.hooksPath", ".husky/_", cwd=repo)
    payload = lib.run_doctor(repo)
    assert payload["status"] == "fail"
    husky = next(check for check in payload["checks"] if check["id"] == "husky_dir")
    assert husky["status"] == "fail"
    assert "charness worktree prepare" in (husky["next_action"] or "")


def test_doctor_husky_marker_present_passes(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    (repo / ".husky" / "_").mkdir(parents=True)
    (repo / ".husky" / "_" / "pre-commit").write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    _git("config", "core.hooksPath", ".husky/_", cwd=repo)
    payload = lib.run_doctor(repo)
    husky = next(check for check in payload["checks"] if check["id"] == "husky_dir")
    assert husky["status"] == "pass"


def test_doctor_husky_v9_default_missing_underscore_fails(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    (repo / ".husky").mkdir()
    (repo / ".husky" / "pre-commit").write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    _git("config", "core.hooksPath", ".husky", cwd=repo)
    payload = lib.run_doctor(repo)
    husky = next(check for check in payload["checks"] if check["id"] == "husky_dir")
    assert husky["status"] == "fail"
    assert "_" in (husky["detail"] or "")


def test_doctor_husky_v9_default_with_underscore_passes(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    (repo / ".husky" / "_").mkdir(parents=True)
    (repo / ".husky" / "_" / "h").write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    _git("config", "core.hooksPath", ".husky", cwd=repo)
    payload = lib.run_doctor(repo)
    husky = next(check for check in payload["checks"] if check["id"] == "husky_dir")
    assert husky["status"] == "pass"


def test_manifest_inline_array_argv_emits_targeted_error(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    _write_manifest(
        repo,
        "version: 1\nprepare:\n  commands:\n    - id: hi\n      argv: '[echo, hi]'\n",
    )
    payload = lib.run_doctor(repo)
    assert payload["status"] == "fail"
    assert payload["manifest"]["valid"] is False
    assert any("inline YAML array" in err for err in payload["manifest"]["errors"])


def test_manifest_invalid_version_returns_fail(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    _write_manifest(repo, "version: 2\nprepare:\n  commands:\n    - id: hi\n      argv:\n        - echo\n        - hi\n")
    payload = lib.run_doctor(repo)
    assert payload["status"] == "fail"
    assert payload["manifest"]["valid"] is False
    assert any("version" in err for err in payload["manifest"]["errors"])


def test_manifest_doctor_check_runs_extra_command(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    _write_manifest(
        repo,
        (
            "version: 1\n"
            "prepare:\n"
            "  commands:\n"
            "    - id: noop\n"
            "      argv:\n"
            "        - '/bin/true'\n"
            "doctor:\n"
            "  checks:\n"
            "    - id: env_probe\n"
            "      next_action_hint: 'rerun setup'\n"
            "      argv:\n"
            "        - '/bin/true'\n"
        ),
    )
    payload = lib.run_doctor(repo)
    env_probe = next(check for check in payload["checks"] if check["id"] == "env_probe")
    assert env_probe["status"] == "pass"
    assert env_probe["source"] == "manifest"


def test_manifest_doctor_check_failure_surfaces_next_action(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    _write_manifest(
        repo,
        (
            "version: 1\n"
            "prepare:\n"
            "  commands:\n"
            "    - id: noop\n"
            "      argv:\n"
            "        - '/bin/true'\n"
            "doctor:\n"
            "  checks:\n"
            "    - id: failing_probe\n"
            "      next_action_hint: 'do the thing'\n"
            "      argv:\n"
            "        - '/bin/false'\n"
        ),
    )
    payload = lib.run_doctor(repo)
    assert payload["status"] == "fail"
    failing = next(check for check in payload["checks"] if check["id"] == "failing_probe")
    assert failing["status"] == "fail"
    assert payload["next_action"] == "do the thing"


def test_prepare_runs_commands_when_doctor_was_passing_with_force(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    marker = repo / "marker.txt"
    _write_manifest(
        repo,
        (
            "version: 1\n"
            "prepare:\n"
            "  commands:\n"
            "    - id: write-marker\n"
            "      argv:\n"
            "        - sh\n"
            "        - -c\n"
            f"        - 'echo ok > {marker}'\n"
        ),
    )
    payload = lib.run_prepare(repo, force=True)
    assert payload["status"] == "pass"
    assert payload["executed"][0]["id"] == "write-marker"
    assert marker.read_text(encoding="utf-8").strip() == "ok"


def test_prepare_skipped_when_doctor_passes_without_force(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    _write_manifest(
        repo,
        (
            "version: 1\n"
            "prepare:\n"
            "  commands:\n"
            "    - id: should-not-run\n"
            "      argv:\n"
            "        - '/bin/false'\n"
        ),
    )
    payload = lib.run_prepare(repo, force=False)
    assert payload["status"] == "pass"
    assert payload["executed"] == []
    assert payload.get("skipped")


def test_prepare_command_failure_surfaces_fail(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    _write_manifest(
        repo,
        (
            "version: 1\n"
            "prepare:\n"
            "  commands:\n"
            "    - id: boom\n"
            "      argv:\n"
            "        - '/bin/false'\n"
        ),
    )
    payload = lib.run_prepare(repo, force=True)
    assert payload["status"] == "fail"
    assert payload["executed"][0]["exit_code"] == 1
    assert "prepare command failed" in (payload["next_action"] or "")


def test_prepare_no_manifest_emits_actionable_next_step(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    payload = lib.run_prepare(repo)
    assert payload["status"] == "fail"
    assert ".agents/worktree-adapter.yaml" in (payload["next_action"] or "")


def test_cli_doctor_subcommand_returns_json(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    result = subprocess.run(
        [sys.executable, str(ROOT / "charness"), "worktree", "doctor", "--repo-root", str(repo), "--json"],
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    assert '"status": "pass"' in result.stdout


def test_cli_prepare_subcommand_runs_command(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    marker = repo / "marker.txt"
    _write_manifest(
        repo,
        (
            "version: 1\n"
            "prepare:\n"
            "  commands:\n"
            "    - id: write-marker\n"
            "      argv:\n"
            "        - sh\n"
            "        - -c\n"
            f"        - 'echo cli > {marker}'\n"
        ),
    )
    result = subprocess.run(
        [
            sys.executable,
            str(ROOT / "charness"),
            "worktree",
            "prepare",
            "--repo-root",
            str(repo),
            "--force",
            "--json",
        ],
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    assert marker.read_text(encoding="utf-8").strip() == "cli"


def _install_path_shim(tmp_path: Path) -> tuple[Path, Path]:
    home = tmp_path / "home"
    managed = home / ".agents" / "src" / "charness"
    managed.parent.mkdir(parents=True)
    managed.symlink_to(ROOT)
    shim_dir = home / ".local" / "bin"
    shim_dir.mkdir(parents=True)
    shim = shim_dir / "charness"
    shutil.copy2(ROOT / "charness", shim)
    return home, shim


def test_cli_worktree_doctor_via_path_shim_routes_to_managed_checkout(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    home, shim = _install_path_shim(tmp_path)
    result = subprocess.run(
        [
            sys.executable,
            str(shim),
            "worktree",
            "doctor",
            "--home-root",
            str(home),
            "--repo-root",
            str(repo),
            "--json",
        ],
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    payload = json.loads(result.stdout)
    assert payload["status"] == "pass"


def test_cli_worktree_doctor_via_path_shim_missing_checkout_emits_actionable_error(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    home = tmp_path / "home-empty"
    shim_dir = home / ".local" / "bin"
    shim_dir.mkdir(parents=True)
    shim = shim_dir / "charness"
    shutil.copy2(ROOT / "charness", shim)
    result = subprocess.run(
        [
            sys.executable,
            str(shim),
            "worktree",
            "doctor",
            "--home-root",
            str(home),
            "--repo-root",
            str(repo),
            "--json",
        ],
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode != 0
    assert "charness init" in result.stderr
    assert "--charness-checkout" in result.stderr


def test_cli_worktree_doctor_via_path_shim_explicit_checkout(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    home = tmp_path / "home-explicit"
    shim_dir = home / ".local" / "bin"
    shim_dir.mkdir(parents=True)
    shim = shim_dir / "charness"
    shutil.copy2(ROOT / "charness", shim)
    result = subprocess.run(
        [
            sys.executable,
            str(shim),
            "worktree",
            "doctor",
            "--home-root",
            str(home),
            "--charness-checkout",
            str(ROOT),
            "--repo-root",
            str(repo),
            "--json",
        ],
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    payload = json.loads(result.stdout)
    assert payload["status"] == "pass"


def test_disable_canonical_check_honored(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    hooks_dir = repo / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    shim = hooks_dir / "pre-commit"
    shim.write_text("#!/bin/sh\nexec lefthook run pre-commit\n", encoding="utf-8")
    shim.chmod(0o755)
    _write_manifest(
        repo,
        (
            "version: 1\n"
            "prepare:\n"
            "  commands:\n"
            "    - id: noop\n"
            "      argv:\n"
            "        - '/bin/true'\n"
            "doctor:\n"
            "  disable_canonical_checks:\n"
            "    - lefthook_shim\n"
        ),
    )
    payload = lib.run_doctor(repo)
    assert all(check["id"] != "lefthook_shim" for check in payload["checks"])
