from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

from scripts import worktree_doctor_checks as checks
from scripts import worktree_doctor_lib as lib
from tests.charness_cli.worktree_fixtures import copy_worktree_seed

ROOT = Path(__file__).resolve().parents[2]


def _git(*args: str, cwd: Path) -> None:
    subprocess.run(["git", *args], cwd=cwd, check=True, capture_output=True, text=True)


def _make_git_worktree(tmp_path: Path) -> Path:
    return copy_worktree_seed(tmp_path, "repo")


def _write_manifest(repo: Path, body: str) -> None:
    (repo / ".agents").mkdir(exist_ok=True)
    (repo / ".agents" / "worktree-adapter.yaml").write_text(body, encoding="utf-8")


def _plain_repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    return repo


def _doctor_payload(
    status: str = "pass", checks: tuple[dict[str, str], ...] = (), next_step: str | None = None
) -> dict[str, object]:
    return {"status": status, "checks": list(checks), "next_step": next_step}


def test_doctor_no_manifest_passes_canonical_only(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    payload = lib.run_doctor(repo)
    assert payload["status"] == "pass"
    assert payload["manifest"]["found"] is False
    assert payload["_checkout"] == {"own_dir": str((repo / ".git").resolve())}
    ids = {check["id"]: check["status"] for check in payload["checks"]}
    assert ids["git_common_dir"] == "pass"
    assert ids["hooks_path"] == "skipped"
    assert ids["lefthook_shim"] == "skipped"
    assert ids["husky_dir"] == "skipped"


def test_doctor_lefthook_shim_missing_node_modules_fails(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    repo = _make_git_worktree(tmp_path)
    hooks_dir = repo / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    shim = hooks_dir / "pre-commit"
    shim.write_text(
        "#!/bin/sh\n"
        '# Code generated by lefthook. DO NOT EDIT.\n'
        'exec ./node_modules/lefthook-linux-x64/bin/lefthook run pre-commit "$@"\n',
        encoding="utf-8",
    )
    shim.chmod(0o755)
    isolated_path = str(Path(sys.executable).resolve().parent) + os.pathsep + "/usr/bin" + os.pathsep + "/bin"
    monkeypatch.setenv("PATH", isolated_path)
    payload = lib.run_doctor(repo)
    assert payload["status"] == "fail"
    lefthook = next(check for check in payload["checks"] if check["id"] == "lefthook_shim")
    assert lefthook["status"] == "fail"
    assert "charness worktree prepare" in (lefthook["next_step"] or "")


def test_doctor_lefthook_shim_resolves_via_node_modules(tmp_path: Path) -> None:
    repo = _plain_repo(tmp_path)
    hooks_dir = repo / "hooks"
    hooks_dir.mkdir()
    shim = hooks_dir / "pre-commit"
    shim.write_text("#!/bin/sh\nexec lefthook run pre-commit\n", encoding="utf-8")
    shim.chmod(0o755)
    binary_dir = repo / "node_modules" / "lefthook-linux-x64" / "bin"
    binary_dir.mkdir(parents=True)
    binary = binary_dir / "lefthook"
    binary.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    binary.chmod(0o755)
    result = checks._check_lefthook_shim(repo, hooks_dir)
    assert result.status == checks.PASS


def test_doctor_husky_marker_missing_fails(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    _git("config", "core.hooksPath", ".husky/_", cwd=repo)
    payload = lib.run_doctor(repo)
    assert payload["status"] == "fail"
    husky = next(check for check in payload["checks"] if check["id"] == "husky_dir")
    assert husky["status"] == "fail"
    assert "charness worktree prepare" in (husky["next_step"] or "")


def test_doctor_husky_marker_present_passes(tmp_path: Path) -> None:
    repo = _plain_repo(tmp_path)
    (repo / ".husky" / "_").mkdir(parents=True)
    (repo / ".husky" / "_" / "pre-commit").write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    result = checks._check_husky_dir(repo, ".husky/_")
    assert result.status == checks.PASS


def test_doctor_husky_v9_default_missing_underscore_fails(tmp_path: Path) -> None:
    repo = _plain_repo(tmp_path)
    (repo / ".husky").mkdir()
    (repo / ".husky" / "pre-commit").write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    result = checks._check_husky_dir(repo, ".husky")
    assert result.status == checks.FAIL
    assert "_" in (result.detail or "")


def test_doctor_husky_v9_default_with_underscore_passes(tmp_path: Path) -> None:
    repo = _plain_repo(tmp_path)
    (repo / ".husky" / "_").mkdir(parents=True)
    (repo / ".husky" / "_" / "h").write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    result = checks._check_husky_dir(repo, ".husky")
    assert result.status == checks.PASS


def test_manifest_inline_array_argv_emits_targeted_error(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    _write_manifest(
        repo,
        "version: 1\nprepare:\n  commands:\n    - id: hi\n      argv: '[echo, hi]'\n",
    )
    payload = lib.run_doctor(repo)
    assert payload["status"] == "fail"
    assert payload["manifest"]["valid"] is False
    assert any("inline YAML array" in err for err in payload["manifest"]["errors"])


def test_manifest_invalid_version_returns_fail(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    _write_manifest(repo, "version: 2\nprepare:\n  commands:\n    - id: hi\n      argv:\n        - echo\n        - hi\n")
    payload = lib.run_doctor(repo)
    assert payload["status"] == "fail"
    assert payload["manifest"]["valid"] is False
    assert any("version" in err for err in payload["manifest"]["errors"])


@pytest.mark.parametrize(
    ("scalar", "expected"),
    [
        ("true", "manifest.version must be an integer"),
        ('"1"', "manifest.version must be an integer"),
        ("2", "manifest.version must be 1"),
    ],
)
def test_manifest_version_is_reconciled_by_the_shared_check(
    tmp_path: Path, scalar: str, expected: str
) -> None:
    """`version: true` is the row a hand-rolled `!= 1` cannot refuse, because
    `True == 1` in Python. This manifest selects the argv `worktree prepare` executes,
    so accepting a schema version this reader never spoke is a subprocess trust boundary,
    not a cosmetic one. The unsupported-integer row is the polarity control: it proves
    the shared check did not simply start accepting everything.
    """
    repo = _make_git_worktree(tmp_path)
    _write_manifest(
        repo,
        f"version: {scalar}\nprepare:\n  commands:\n    - id: hi\n      argv:\n        - echo\n        - hi\n",
    )

    payload = lib.run_doctor(repo)

    assert payload["status"] == "fail"
    assert payload["manifest"]["valid"] is False
    assert expected in payload["manifest"]["errors"]
    # A refused manifest must not hand its argv back out as authoritative. The public
    # payload does not carry `data`, so read the manifest state that produced it.
    assert lib.load_manifest(repo).data == {}


def test_manifest_without_a_version_is_still_refused(tmp_path: Path) -> None:
    """Absent is legal for a resolver and NOT legal here: this manifest has always
    required a declared version, and the shared check keeps that by passing required."""
    repo = _make_git_worktree(tmp_path)
    _write_manifest(repo, "prepare:\n  commands:\n    - id: hi\n      argv:\n        - echo\n        - hi\n")

    payload = lib.run_doctor(repo)

    assert payload["manifest"]["valid"] is False
    assert "manifest.version is required" in payload["manifest"]["errors"]


def test_manifest_doctor_check_runs_extra_command(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _make_git_worktree(tmp_path)
    monkeypatch.setattr(lib, "run_canonical_checks", lambda *_args, **_kwargs: [])
    _write_manifest(
        repo,
        (
            "version: 1\n"
            "prepare:\n"
            "  commands:\n"
            "    - id: noop\n"
            "      argv:\n"
            "        - '/bin/true'\n"
            "doctor:\n"
            "  checks:\n"
            "    - id: env_probe\n"
            "      next_action_hint: 'rerun setup'\n"
            "      argv:\n"
            "        - '/bin/true'\n"
        ),
    )
    payload = lib.run_doctor(repo)
    env_probe = next(check for check in payload["checks"] if check["id"] == "env_probe")
    assert env_probe["status"] == "pass"
    assert env_probe["source"] == "manifest"


def test_manifest_doctor_check_failure_surfaces_next_step(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _make_git_worktree(tmp_path)
    monkeypatch.setattr(lib, "run_canonical_checks", lambda *_args, **_kwargs: [])
    _write_manifest(
        repo,
        (
            "version: 1\n"
            "prepare:\n"
            "  commands:\n"
            "    - id: noop\n"
            "      argv:\n"
            "        - '/bin/true'\n"
            "doctor:\n"
            "  checks:\n"
            "    - id: failing_probe\n"
            "      next_action_hint: 'do the thing'\n"
            "      argv:\n"
            "        - '/bin/false'\n"
        ),
    )
    payload = lib.run_doctor(repo)
    assert payload["status"] == "fail"
    failing = next(check for check in payload["checks"] if check["id"] == "failing_probe")
    assert failing["status"] == "fail"
    assert payload["next_step"] == "do the thing"
    # The human-text renderer that used to prefix this with "NEXT: " is gone; the
    # actionable step now has to reach the operator through the command payload
    # itself, at the top level, as the manifest's own hint rather than the
    # generic fallback.
    result = subprocess.run(
        [sys.executable, str(ROOT / "charness"), "worktree", "doctor", "--repo-root", str(repo)],
        check=False,
        capture_output=True,
        text=True,
    )
    emitted = yaml.safe_load(result.stdout)
    assert emitted["status"] == "fail"
    assert emitted["next_step"] == "do the thing"


def test_prepare_with_passing_commands_but_failing_doctor_surfaces_next_step(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _make_git_worktree(tmp_path)
    calls = 0

    def fake_doctor(*_args, **_kwargs):
        nonlocal calls
        calls += 1
        return _doctor_payload(
            "pass" if calls == 1 else "fail",
            next_step="rerun setup",
        )

    monkeypatch.setattr(lib, "run_doctor", fake_doctor)
    _write_manifest(
        repo,
        (
            "version: 1\n"
            "prepare:\n"
            "  commands:\n"
            "    - id: noop\n"
            "      argv:\n"
            "        - '/bin/true'\n"
            "doctor:\n"
            "  checks:\n"
            "    - id: still_failing\n"
            "      argv:\n"
            "        - '/bin/false'\n"
        ),
    )
    payload = lib.run_prepare(repo)
    assert payload["status"] == "fail"
    assert payload["next_step"] == payload["doctor"]["next_step"]
    assert payload["next_step"]
    # Renderer deleted: the post-prepare doctor's next step must still surface at
    # the top level of the emitted prepare payload, not only nested under
    # `doctor`, so the operator reads it without digging.
    result = subprocess.run(
        [sys.executable, str(ROOT / "charness"), "worktree", "prepare", "--repo-root", str(repo)],
        check=False,
        capture_output=True,
        text=True,
    )
    emitted = yaml.safe_load(result.stdout)
    assert emitted["status"] == "fail"
    assert emitted["next_step"] == emitted["doctor"]["next_step"]
    assert emitted["next_step"]


def test_prepare_runs_commands_when_doctor_was_passing_with_force(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _make_git_worktree(tmp_path)
    monkeypatch.setattr(lib, "run_doctor", lambda *_args, **_kwargs: _doctor_payload())
    marker = repo / "marker.txt"
    _write_manifest(
        repo,
        (
            "version: 1\n"
            "prepare:\n"
            "  commands:\n"
            "    - id: write-marker\n"
            "      argv:\n"
            "        - sh\n"
            "        - -c\n"
            f"        - 'echo ok > {marker}'\n"
        ),
    )
    payload = lib.run_prepare(repo, force=True)
    assert payload["status"] == "pass"
    assert payload["executed"][0]["id"] == "write-marker"
    assert marker.read_text(encoding="utf-8").strip() == "ok"


def test_prepare_runs_when_doctor_passes_without_declared_coverage(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _make_git_worktree(tmp_path)
    monkeypatch.setattr(lib, "run_doctor", lambda *_args, **_kwargs: _doctor_payload())
    _write_manifest(
        repo,
        (
            "version: 1\n"
            "prepare:\n"
            "  skip_if_doctor_passes: true\n"
            "  commands:\n"
            "    - id: should-not-run\n"
            "      argv:\n"
            "        - '/bin/false'\n"
        ),
    )
    payload = lib.run_prepare(repo, force=False)
    assert payload["status"] == "fail"
    assert payload["executed"][0]["id"] == "should-not-run"
    assert payload["executed"][0]["exit_code"] == 1
    assert payload["coverage"] == {
        "established": False,
        "prepare_command_ids": ["should-not-run"],
        "doctor_check_ids": [],
        "intersection": [],
        "uncovered_prepare_command_ids": ["should-not-run"],
    }
    assert "skipped" not in payload


def test_prepare_skips_when_passing_doctor_declares_coverage(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _make_git_worktree(tmp_path)
    monkeypatch.setattr(
        lib,
        "run_doctor",
        lambda *_args, **_kwargs: _doctor_payload(
            checks=({"id": "dependencies-ready", "status": "pass"},)
        ),
    )
    _write_manifest(
        repo,
        (
            "version: 1\n"
            "prepare:\n"
            "  skip_if_doctor_passes: true\n"
            "  commands:\n"
            "    - id: install-deps\n"
            "      argv:\n"
            "        - '/bin/false'\n"
            "doctor:\n"
            "  checks:\n"
            "    - id: dependencies-ready\n"
            "      covers:\n"
            "        - install-deps\n"
            "      argv:\n"
            "        - '/bin/true'\n"
        ),
    )

    payload = lib.run_prepare(repo, force=False)

    assert payload["status"] == "pass"
    assert payload["executed"] == []
    assert payload["coverage"] == {
        "established": True,
        "prepare_command_ids": ["install-deps"],
        "doctor_check_ids": ["dependencies-ready"],
        "intersection": ["install-deps"],
        "uncovered_prepare_command_ids": [],
    }
    assert "install-deps" in payload["skipped"]
    assert "dependencies-ready" in payload["skipped"]


def test_prepare_command_failure_surfaces_fail(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _make_git_worktree(tmp_path)
    monkeypatch.setattr(lib, "run_doctor", lambda *_args, **_kwargs: _doctor_payload())
    _write_manifest(
        repo,
        (
            "version: 1\n"
            "prepare:\n"
            "  commands:\n"
            "    - id: boom\n"
            "      argv:\n"
            "        - '/bin/false'\n"
        ),
    )
    payload = lib.run_prepare(repo, force=True)
    assert payload["status"] == "fail"
    assert payload["executed"][0]["exit_code"] == 1
    assert "prepare command failed" in (payload["next_step"] or "")


def test_prepare_no_manifest_emits_actionable_next_step(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    payload = lib.run_prepare(repo)
    assert payload["status"] == "fail"
    assert ".agents/worktree-adapter.yaml" in (payload["next_step"] or "")


def test_cli_doctor_subcommand_returns_yaml(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    result = subprocess.run(
        [sys.executable, str(ROOT / "charness"), "worktree", "doctor", "--repo-root", str(repo)],
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    assert yaml.safe_load(result.stdout)["status"] == "pass"


def test_cli_prepare_subcommand_runs_command(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    marker = repo / "marker.txt"
    _write_manifest(
        repo,
        (
            "version: 1\n"
            "prepare:\n"
            "  commands:\n"
            "    - id: write-marker\n"
            "      argv:\n"
            "        - sh\n"
            "        - -c\n"
            f"        - 'echo cli > {marker}'\n"
        ),
    )
    result = subprocess.run(
        [
            sys.executable,
            str(ROOT / "charness"),
            "worktree",
            "prepare",
            "--repo-root",
            str(repo),
            "--force",
        ],
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    assert marker.read_text(encoding="utf-8").strip() == "cli"


def _install_path_shim(tmp_path: Path) -> tuple[Path, Path]:
    home = tmp_path / "home"
    managed = home / ".agents" / "src" / "charness"
    managed.parent.mkdir(parents=True)
    managed.symlink_to(ROOT)
    shim_dir = home / ".local" / "bin"
    shim_dir.mkdir(parents=True)
    shim = shim_dir / "charness"
    shutil.copy2(ROOT / "charness", shim)
    return home, shim


def test_cli_worktree_doctor_via_path_shim_routes_to_managed_checkout(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    home, shim = _install_path_shim(tmp_path)
    result = subprocess.run(
        [
            sys.executable,
            str(shim),
            "worktree",
            "doctor",
            "--home-root",
            str(home),
            "--repo-root",
            str(repo),
        ],
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    payload = yaml.safe_load(result.stdout)
    assert payload["status"] == "pass"


def test_cli_worktree_doctor_via_path_shim_missing_checkout_emits_actionable_error(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    home = tmp_path / "home-empty"
    shim_dir = home / ".local" / "bin"
    shim_dir.mkdir(parents=True)
    shim = shim_dir / "charness"
    shutil.copy2(ROOT / "charness", shim)
    result = subprocess.run(
        [
            sys.executable,
            str(shim),
            "worktree",
            "doctor",
            "--home-root",
            str(home),
            "--repo-root",
            str(repo),
        ],
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode != 0
    assert "charness init" in result.stderr
    assert "--charness-checkout" in result.stderr


def test_cli_worktree_doctor_via_path_shim_explicit_checkout(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    home = tmp_path / "home-explicit"
    shim_dir = home / ".local" / "bin"
    shim_dir.mkdir(parents=True)
    shim = shim_dir / "charness"
    shutil.copy2(ROOT / "charness", shim)
    result = subprocess.run(
        [
            sys.executable,
            str(shim),
            "worktree",
            "doctor",
            "--home-root",
            str(home),
            "--charness-checkout",
            str(ROOT),
            "--repo-root",
            str(repo),
        ],
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    payload = yaml.safe_load(result.stdout)
    assert payload["status"] == "pass"


def test_disable_canonical_check_honored(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)
    hooks_dir = repo / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    shim = hooks_dir / "pre-commit"
    shim.write_text("#!/bin/sh\nexec lefthook run pre-commit\n", encoding="utf-8")
    shim.chmod(0o755)
    _write_manifest(
        repo,
        (
            "version: 1\n"
            "prepare:\n"
            "  commands:\n"
            "    - id: noop\n"
            "      argv:\n"
            "        - '/bin/true'\n"
            "doctor:\n"
            "  disable_canonical_checks:\n"
            "    - lefthook_shim\n"
        ),
    )
    payload = lib.run_doctor(repo)
    assert all(check["id"] != "lefthook_shim" for check in payload["checks"])

def _git_out(*args: str, cwd: Path) -> str:
    result = subprocess.run(
        ["git", *args], cwd=cwd, check=True, capture_output=True, text=True
    )
    return result.stdout


# --- SC10: worktree isolation for write-capable agents -----------------------
#
# Owner ruling 2026-08-15 retired the refusal framing. There is no refusal
# message and a mutating git op still SUCCEEDS -- the criterion is that it can no
# longer reach the parent's tree or index, because the agent does not share them.
# So the positive case here is not "the op was blocked"; it is "the op landed
# somewhere that harms nothing", and the negative case is the one that would be
# lost if isolation were achieved by taking the shell away instead.


def test_the_main_worktree_reports_that_it_is_not_isolated(tmp_path: Path) -> None:
    repo = _make_git_worktree(tmp_path)

    payload = lib.run_doctor(repo)
    check = next(item for item in payload["checks"] if item["id"] == "worktree_isolation")

    # Reported as a FACT, and skipped rather than failed: an operator working
    # directly in the main worktree is doing nothing wrong, and a check that
    # failed for them unasked is one they would learn to ignore.
    assert check["status"] == "skipped"
    assert "IS the main worktree" in check["detail"]
    assert payload["status"] == "pass"


def test_requiring_isolation_fails_in_the_main_worktree_and_names_the_remedy(
    tmp_path: Path,
) -> None:
    repo = _make_git_worktree(tmp_path)

    payload = lib.run_doctor(repo, require_isolation=True)
    check = next(item for item in payload["checks"] if item["id"] == "worktree_isolation")

    assert check["status"] == "fail"
    assert payload["status"] == "fail"
    # A verdict an agent cannot act on is a verdict it will route around.
    assert "charness worktree create" in payload["next_step"]


def test_a_linked_worktree_is_isolated_and_its_own_commits_still_succeed(
    tmp_path: Path,
) -> None:
    """The positive case, plus the negative direction stated for what it is.

    The PASS assertion is a regression guard on this repo's check. The commit
    assertions below are NOT: they are a property of git, and they would still
    hold with `_check_worktree_isolation` deleted. They are kept because they pin
    the DEFINITION of isolation this repo adopted -- an agent that can still
    commit in its own tree -- against the typed-agent mechanism the ruling
    rejected, which achieves "the parent's index was untouched" by taking the
    shell away. No suite can exercise that rejected mechanism, so this documents
    the boundary rather than defending it. (Round 1 refuted the first docstring,
    which claimed it guarded that failure mode.)
    """
    repo = _make_git_worktree(tmp_path)
    linked = tmp_path / "agent-worktree"
    _git("worktree", "add", "-b", "agent-slice", str(linked), cwd=repo)

    payload = lib.run_doctor(linked, require_isolation=True)
    check = next(item for item in payload["checks"] if item["id"] == "worktree_isolation")
    assert check["status"] == "pass", check["detail"]
    assert "its own git dir" in check["detail"]

    main_head_before = _git_out("rev-parse", "HEAD", cwd=repo).strip()
    main_status_before = _git_out("status", "--porcelain", cwd=repo)

    # The agent does its write-capable work, including the exact operations the
    # retired prose rule forbade.
    (linked / "agent-file.txt").write_text("written by the agent\n", encoding="utf-8")
    _git("add", "agent-file.txt", cwd=linked)
    _git("-c", "user.email=a@b.c", "-c", "user.name=agent", "commit", "-m", "agent", cwd=linked)
    _git("checkout", "-b", "another-branch", cwd=linked)

    # It worked, in its own tree.
    assert (linked / "agent-file.txt").exists()
    assert _git_out("rev-parse", "HEAD", cwd=linked).strip() != main_head_before

    # And the parent's tree and index never moved.
    assert _git_out("rev-parse", "HEAD", cwd=repo).strip() == main_head_before
    assert _git_out("status", "--porcelain", cwd=repo) == main_status_before
    assert not (repo / "agent-file.txt").exists()


def test_isolation_is_unknown_rather_than_confirmed_in_a_bare_repository(
    tmp_path: Path,
) -> None:
    # The direction that matters: an undecidable case must never report PASS.
    # Reading "not the main worktree" off a repo that has no main worktree would
    # certify isolation that was never established.
    bare = tmp_path / "bare.git"
    subprocess.run(
        ["git", "init", "--bare", str(bare)], check=True, capture_output=True, text=True
    )

    payload = lib.run_doctor(bare, require_isolation=True)
    check = next(item for item in payload["checks"] if item["id"] == "worktree_isolation")

    assert check["status"] == "fail"
    assert "UNKNOWN" in check["detail"]


# The false-PASS cases a round-1 reviewer found in the FIRST version of this
# check, which decided isolation by comparing the checkout path against the main
# worktree. Each one reported "isolated" while writing the parent's index. They
# are parametrized together because they are one defect, not three: the old code
# asked where the directory SITS instead of where its index IS.
def test_configurations_that_share_the_parent_index_are_never_reported_isolated(
    tmp_path: Path,
) -> None:
    repo = _make_git_worktree(tmp_path)

    # 1. A subdirectory of the main worktree -- one plausible --repo-root typo.
    (repo / "scripts").mkdir()
    payload = lib.run_doctor(repo / "scripts", require_isolation=True)
    check = next(item for item in payload["checks"] if item["id"] == "worktree_isolation")
    assert check["status"] == "fail", "a subdirectory of the main worktree is not isolated"

    # 2. The main worktree's own git dir.
    payload = lib.run_doctor(repo / ".git", require_isolation=True)
    check = next(item for item in payload["checks"] if item["id"] == "worktree_isolation")
    assert check["status"] != "pass", "the main worktree's gitdir is not an isolated checkout"


def test_a_bare_repo_named_dot_git_is_unknown_not_isolated(tmp_path: Path) -> None:
    # The old check's bare-repo safety rested on the gitdir being NAMED `.git`,
    # so a bare repo at `/srv/site/.git` -- the shape `--separate-git-dir` and
    # `clone --bare` both produce -- passed as isolated. `--is-bare-repository`
    # asks the question directly.
    site = tmp_path / "site"
    site.mkdir()
    subprocess.run(
        ["git", "init", "--bare", str(site / ".git")], check=True, capture_output=True, text=True
    )

    payload = lib.run_doctor(site / ".git", require_isolation=True)
    check = next(item for item in payload["checks"] if item["id"] == "worktree_isolation")

    assert check["status"] == "fail"
    assert "UNKNOWN" in check["detail"]


def test_ambient_git_dir_cannot_redirect_the_verdict(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # `git rev-parse` answers about the repository it DISCOVERS, and GIT_DIR
    # overrides discovery. Inherited from a git hook or `git rebase --exec`, it
    # would silently produce a verdict about a repository the caller never named.
    repo = _make_git_worktree(tmp_path)
    linked = tmp_path / "agent-worktree"
    _git("worktree", "add", "-b", "ambient-probe", str(linked), cwd=repo)
    monkeypatch.setenv("GIT_DIR", str(repo / ".git"))
    monkeypatch.setenv("GIT_WORK_TREE", str(repo))

    payload = lib.run_doctor(linked, require_isolation=True)
    check = next(item for item in payload["checks"] if item["id"] == "worktree_isolation")

    assert check["status"] == "pass", "the ambient GIT_DIR displaced the named checkout"


def test_a_linked_worktree_reports_isolation_without_the_flag_too(tmp_path: Path) -> None:
    # The default direction: isolation is a FACT on every run, not something that
    # only exists when someone asks for it. Only the main-worktree direction of
    # the default was covered before.
    repo = _make_git_worktree(tmp_path)
    linked = tmp_path / "agent-worktree"
    _git("worktree", "add", "-b", "fact-probe", str(linked), cwd=repo)

    payload = lib.run_doctor(linked)
    check = next(item for item in payload["checks"] if item["id"] == "worktree_isolation")

    assert check["status"] == "pass"
    assert payload["status"] == "pass"


def test_a_repo_local_adapter_cannot_disable_the_isolation_check(tmp_path: Path) -> None:
    """Deliberate, and pinned because nothing stated it.

    The adapter lives INSIDE the agent's own worktree. If `worktree_isolation`
    were disableable there, the checkout being audited could switch off the
    check the parent required -- so `CANONICAL_CHECK_IDS` deliberately omits it
    and the manifest validator refuses the id.
    """
    repo = _make_git_worktree(tmp_path)
    _write_manifest(
        repo,
        "version: 1\ndoctor:\n  disable_canonical_checks:\n    - worktree_isolation\n",
    )

    payload = lib.run_doctor(repo)

    assert payload["manifest"]["valid"] is False
    assert any("worktree_isolation" in error for error in payload["manifest"]["errors"])
