from __future__ import annotations

import sys
from pathlib import Path
from types import SimpleNamespace

from runtime_bootstrap import import_repo_module

from .support import ROOT, run_script

_check_plugin_doc_links = import_repo_module(
    ROOT / "scripts/check_plugin_doc_links.py", "scripts.check_plugin_doc_links"
)

# The two fixtures below are the REAL confirmed defects from
# https://github.com/corca-ai/charness/issues/479, transcribed from the live tree
# on 2026-08-04, not invented shapes. A checker proven only against a defect its
# own author imagined is proven against the author, not against the class.
REAL_ESCAPE_DOC = "plugins/charness/support/README.md"
REAL_ESCAPE_LINK = "../../scripts/sync_support.py"
REAL_MISSING_DOC = "plugins/charness/shared/references/agent-assessment-invariant.md"
REAL_MISSING_LINK = "../../public/hitl/scripts/check_chunk_contract.py"


def run_check(monkeypatch, capsys, *args: str) -> SimpleNamespace:
    monkeypatch.setattr(sys, "argv", ["check_plugin_doc_links.py", *args])
    try:
        returncode = _check_plugin_doc_links.main()
    except _check_plugin_doc_links.ValidationError as exc:
        print(str(exc), file=sys.stderr)
        returncode = 1
    captured = capsys.readouterr()
    return SimpleNamespace(returncode=returncode, stdout=captured.out, stderr=captured.err)


def write_doc(repo: Path, rel_path: str, body: str) -> None:
    path = repo / rel_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def test_refuses_the_real_escaping_link_from_the_shipped_support_readme(
    tmp_path: Path, monkeypatch, capsys
) -> None:
    """`plugins/charness/support/README.md:26` resolves to `plugins/scripts/`, which exists in no tree."""
    repo = tmp_path / "repo"
    # The escape target is created OUTSIDE the plugin root on purpose: the defect
    # is not that the file is absent from the world, it is that the file is absent
    # from what a consumer installed. A checker that only tested existence would
    # pass this fixture and still ship the defect.
    write_doc(repo, "scripts/sync_support.py", "# real, and unreachable from the mirror\n")
    write_doc(repo, REAL_ESCAPE_DOC, f"Regenerated by [`sync`]({REAL_ESCAPE_LINK}) instead of by hand.\n")

    result = run_check(monkeypatch, capsys, "--repo-root", str(repo))

    assert result.returncode == 1
    assert REAL_ESCAPE_LINK in result.stderr
    assert "escape" in result.stderr


def test_refuses_the_real_kind_flattened_link_that_never_leaves_the_plugin_root(
    tmp_path: Path, monkeypatch, capsys
) -> None:
    """The exporter flattens `skills/<kind>/<skill>/` to `skills/<skill>/`, so `../../public/hitl/...` names nothing.

    This one stays inside the plugin root, so an escape-only ruler reports zero on it.
    """
    repo = tmp_path / "repo"
    write_doc(repo, "plugins/charness/skills/hitl/scripts/check_chunk_contract.py", "# post-flattening home\n")
    write_doc(repo, REAL_MISSING_DOC, f"See [contract]({REAL_MISSING_LINK}).\n")

    result = run_check(monkeypatch, capsys, "--repo-root", str(repo))

    assert result.returncode == 1
    assert REAL_MISSING_LINK in result.stderr
    assert "missing" in result.stderr


def test_accepts_the_repaired_form_of_the_kind_flattened_link(tmp_path: Path, monkeypatch, capsys) -> None:
    """Proves the gate BITES on a difference, not on the fixture: same doc, corrected target."""
    repo = tmp_path / "repo"
    write_doc(repo, "plugins/charness/skills/hitl/scripts/check_chunk_contract.py", "# post-flattening home\n")
    write_doc(repo, REAL_MISSING_DOC, "See [contract](../../skills/hitl/scripts/check_chunk_contract.py).\n")

    result = run_check(monkeypatch, capsys, "--repo-root", str(repo))

    assert result.returncode == 0
    assert "Validated relative links in 1 plugin-mirror doc(s)." in result.stdout


def test_accepts_an_authoring_repo_placeholder_replacing_an_escape(tmp_path: Path, monkeypatch, capsys) -> None:
    """The prescribed repair for an escape is a backticked placeholder, so it must pass."""
    repo = tmp_path / "repo"
    write_doc(
        repo,
        REAL_ESCAPE_DOC,
        "Regenerated by `<authoring-repo>/scripts/sync_support.py` instead of by hand.\n",
    )

    result = run_check(monkeypatch, capsys, "--repo-root", str(repo))

    assert result.returncode == 0


def test_ignores_anchors_external_urls_and_bare_targets(tmp_path: Path, monkeypatch, capsys) -> None:
    """None of these carries a consumer-resolvable filesystem claim this gate owns.

    The bare target is deliberately left alone: `check_doc_links.py` owns the
    "must start with ./ or ../" rule on the authoring source these files are
    generated from, and reporting it here too would name one defect twice.
    """
    repo = tmp_path / "repo"
    write_doc(
        repo,
        "plugins/charness/shared/references/notes.md",
        "[a](#section) [b](https://example.com/x.md) [c](mailto:x@example.com) [d](docs/guide.md)\n",
    )

    result = run_check(monkeypatch, capsys, "--repo-root", str(repo))

    assert result.returncode == 0


def test_a_fenced_or_commented_example_of_the_defect_is_not_refused(
    tmp_path: Path, monkeypatch, capsys
) -> None:
    """A doc TEACHING this defect must be able to show it without the gate refusing the doc."""
    repo = tmp_path / "repo"
    write_doc(
        repo,
        "plugins/charness/shared/references/teaching.md",
        "The broken form looks like this:\n\n"
        "```markdown\n"
        "[helper](../../../scripts/runtime_bootstrap.py)\n"
        "```\n\n"
        "<!-- [stale](../../../docs/gone.md) -->\n",
    )

    result = run_check(monkeypatch, capsys, "--repo-root", str(repo))

    assert result.returncode == 0, result.stderr


def test_live_prose_beside_a_fence_is_still_refused(tmp_path: Path, monkeypatch, capsys) -> None:
    """Guards the fence skip from becoming a hole: prose next to an example still counts."""
    repo = tmp_path / "repo"
    write_doc(
        repo,
        "plugins/charness/shared/references/teaching.md",
        "```markdown\n[example](../../../scripts/a.py)\n```\n\nSee [real](../../../scripts/b.py).\n",
    )

    result = run_check(monkeypatch, capsys, "--repo-root", str(repo))

    assert result.returncode == 1
    assert "scripts/b.py" in result.stderr
    assert "scripts/a.py" not in result.stderr


def test_a_prose_wrapped_link_is_still_one_link(tmp_path: Path, monkeypatch, capsys) -> None:
    """Round-2 hole: the fence repair narrowed matching to per-line, and `LINK_RE` spans newlines.

    A link whose text wraps across lines renders as one link and escapes the
    plugin root exactly like an unwrapped one, so a per-line ruler reports a
    clean tree while the defect ships.
    """
    repo = tmp_path / "repo"
    write_doc(
        repo,
        "plugins/charness/shared/references/wrapped.md",
        "See the [agent assessment\ninvariant](../../../scripts/runtime_bootstrap.py) for the rule.\n",
    )

    result = run_check(monkeypatch, capsys, "--repo-root", str(repo))

    assert result.returncode == 1
    assert "escape" in result.stderr


def test_a_mismatched_inner_fence_marker_does_not_invert_the_rest_of_the_document(
    tmp_path: Path, monkeypatch, capsys
) -> None:
    """A `~~~` fence whose body shows a ``` line must not leave the tail marked fenced.

    A plain toggle over `(```|~~~)` flips `in_fence` on the inner line, so every
    later link is skipped as "fenced" and the gate goes green on a real escape.
    """
    repo = tmp_path / "repo"
    write_doc(
        repo,
        "plugins/charness/shared/references/fence.md",
        "Showing how to open a fenced block:\n\n~~~\n```\n~~~\n\n"
        "See [helper](../../../scripts/runtime_bootstrap.py).\n",
    )

    result = run_check(monkeypatch, capsys, "--repo-root", str(repo))

    assert result.returncode == 1
    assert "runtime_bootstrap.py" in result.stderr


def test_live_content_after_a_closing_html_comment_is_scanned(tmp_path: Path, monkeypatch, capsys) -> None:
    """Text after `-->` renders normally, so dropping the whole line hides a live link."""
    repo = tmp_path / "repo"
    write_doc(
        repo,
        "plugins/charness/shared/references/comment.md",
        "<!-- disabled note\n--> See [helper](../../../scripts/runtime_bootstrap.py).\n",
    )

    result = run_check(monkeypatch, capsys, "--repo-root", str(repo))

    assert result.returncode == 1
    assert "runtime_bootstrap.py" in result.stderr


def test_a_markdown_file_directly_under_plugins_has_no_plugin_root(tmp_path: Path, monkeypatch, capsys) -> None:
    """`plugins/NOTES.md` is in no installed package, so it has no reader position to judge from."""
    repo = tmp_path / "repo"
    write_doc(repo, "plugins/NOTES.md", "[gone](../scripts/absent.py)\n")

    result = run_check(monkeypatch, capsys, "--repo-root", str(repo))

    assert result.returncode == 0


def test_link_anchors_are_stripped_before_resolution(tmp_path: Path, monkeypatch, capsys) -> None:
    repo = tmp_path / "repo"
    write_doc(repo, "plugins/charness/shared/references/target.md", "# Target\n")
    write_doc(repo, "plugins/charness/shared/references/notes.md", "[t](./target.md#a-heading)\n")

    result = run_check(monkeypatch, capsys, "--repo-root", str(repo))

    assert result.returncode == 0


def test_reports_every_unfollowable_link_not_only_the_first(tmp_path: Path, monkeypatch, capsys) -> None:
    """A gate that stops at the first defect turns one sweep into N fix-and-rerun rounds."""
    repo = tmp_path / "repo"
    write_doc(
        repo,
        "plugins/charness/shared/references/bootstrap-resolution.md",
        "[a](../../../scripts/runtime_bootstrap.py)\n[b](../../../scripts/repo_layout.py)\n",
    )

    result = run_check(monkeypatch, capsys, "--repo-root", str(repo))

    assert result.returncode == 1
    assert "runtime_bootstrap.py" in result.stderr
    assert "repo_layout.py" in result.stderr


def test_the_live_tree_confirms_the_class_is_not_yet_zero_or_is_repaired(monkeypatch, capsys) -> None:
    """Guards the repair itself: once the 12 are fixed this pins them fixed.

    Runs against the materialized tree rather than a fixture, because the defect
    this gate exists for is a property of the SHIPPED mirror, and a fixture can
    only ever prove the rule, never the tree.
    """
    result = run_check(monkeypatch, capsys, "--repo-root", str(ROOT))

    assert result.returncode == 0, result.stderr


def test_the_success_line_states_what_it_did_not_judge(tmp_path: Path, monkeypatch, capsys) -> None:
    """A gate that skips silently and prints "Validated" reads as full coverage.

    That is the failure this gate's whole lineage is about: three passes over
    #477/#478/#479 reported an honest "0 remaining" under a ruler narrower than
    the class, and none of them said so. So the skip is counted by reason and
    appended to the success line.
    """
    repo = tmp_path / "repo"
    write_doc(repo, "plugins/NOTES.md", "[gone](../scripts/absent.py)\n")
    write_doc(
        repo,
        "plugins/charness/shared/references/teaching.md",
        "```markdown\n[example](../../../scripts/a.py)\n```\n\nFine.\n",
    )

    result = run_check(monkeypatch, capsys, "--repo-root", str(repo))

    assert result.returncode == 0
    assert "1 fenced-or-commented-link" in result.stdout
    assert "1 no-plugin-root" in result.stdout


def test_the_refusal_also_states_what_it_did_not_judge(tmp_path: Path, monkeypatch, capsys) -> None:
    """The skip count must not vanish on the failure path — that is where a reader most needs it."""
    repo = tmp_path / "repo"
    write_doc(
        repo,
        "plugins/charness/shared/references/mixed.md",
        "```markdown\n[example](../../../scripts/a.py)\n```\n\nSee [real](../../../scripts/b.py).\n",
    )

    result = run_check(monkeypatch, capsys, "--repo-root", str(repo))

    assert result.returncode == 1
    assert "1 unfollowable link(s)" in result.stderr
    assert "1 fenced-or-commented-link" in result.stderr


def test_a_doc_outside_the_repo_root_has_no_plugin_root(tmp_path: Path) -> None:
    """`plugin_root_for` must not raise when handed a path outside the tree it was given.

    `Path.relative_to` raises `ValueError` there, and the honest answer is "no
    plugin root", not a crash — a caller resolving a symlinked or absolute doc
    would otherwise take down the whole gate.
    """
    outside = tmp_path / "elsewhere" / "plugins" / "charness" / "notes.md"
    outside.parent.mkdir(parents=True)
    outside.write_text("# notes\n", encoding="utf-8")

    assert _check_plugin_doc_links.plugin_root_for(tmp_path / "repo", outside) is None


def test_a_mirror_doc_with_no_live_prose_is_counted_not_crashed(
    tmp_path: Path, monkeypatch, capsys
) -> None:
    """A file that is entirely fenced has no line to judge, and the skip is counted."""
    repo = tmp_path / "repo"
    write_doc(repo, "plugins/charness/shared/references/all-fence.md", "```\n[x](../../../a.md)\n```\n")

    result = run_check(monkeypatch, capsys, "--repo-root", str(repo))

    assert result.returncode == 0
    assert "1 no-live-prose" in result.stdout


def test_the_script_entrypoint_reports_both_outcomes_as_a_subprocess(tmp_path: Path) -> None:
    """Covers the `__main__` block, which an in-process `main()` call never reaches.

    The exit codes are the gate's actual contract with `run-quality.sh`, the
    pre-commit plan, and CI — none of which import `main()`.
    """
    repo = tmp_path / "repo"
    write_doc(repo, "plugins/charness/shared/references/ok.md", "no links here\n")
    clean = run_script("scripts/check_plugin_doc_links.py", "--repo-root", str(repo))
    assert clean.returncode == 0, clean.stderr
    assert "Validated relative links in 1 plugin-mirror doc(s)." in clean.stdout

    write_doc(repo, "plugins/charness/shared/references/bad.md", "[x](../../../scripts/a.py)\n")
    refused = run_script("scripts/check_plugin_doc_links.py", "--repo-root", str(repo))
    assert refused.returncode == 1
    assert "escape" in refused.stderr


def test_an_absent_mirror_is_unestablished_scope_not_a_clean_verdict(
    tmp_path: Path, monkeypatch, capsys
) -> None:
    """No mirror is not the same as a mirror with nothing wrong in it.

    `/plugins/` is gitignored, and this gate used to scope through
    `git ls-files --others --exclude-standard`, which honors that. So it printed
    the SAME line -- byte for byte -- over a complete 229-doc mirror and over no
    mirror at all. This test is the discriminator that state could not survive.
    """
    bare = tmp_path / "bare"
    bare.mkdir()

    result = run_check(monkeypatch, capsys, "--repo-root", str(bare))

    assert result.returncode == 1
    assert "status: unestablished" in result.stderr
    assert "sync_root_plugin_manifests.py" in result.stderr
    assert "Validated" not in result.stdout


def test_an_empty_mirror_still_passes_because_its_scope_was_established(
    tmp_path: Path, monkeypatch, capsys
) -> None:
    """The other half of the asymmetry: present-and-empty is a real answer."""
    repo = tmp_path / "repo"
    (repo / "plugins").mkdir(parents=True)

    result = run_check(monkeypatch, capsys, "--repo-root", str(repo))

    assert result.returncode == 0
    assert "Validated relative links in 0 plugin-mirror doc(s)." in result.stdout
