#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from collections import Counter
from datetime import date
from pathlib import Path
from typing import Any

from runtime_bootstrap import repo_root_from_script

REPO_ROOT = repo_root_from_script(__file__)
DEFAULT_INVENTORY_PATH = Path("charness-artifacts/find-skills/latest.json")
DEFAULT_OUTPUT_PATH = Path("charness-artifacts/design-studies/issue-57/capability-spectrum.md")

SECTION_SPECS = (
    ("public_skills", "Public Workflow Concepts"),
    ("support_skills", "Support Skill Surfaces"),
    ("support_capabilities", "Support Runtime Capabilities"),
    ("integrations", "External Integrations"),
)


def _as_list(value: object) -> list[object]:
    return value if isinstance(value, list) else []


def _strings(value: object) -> list[str]:
    return [item for item in _as_list(value) if isinstance(item, str)]


def _text(value: object, *, default: str = "") -> str:
    return value if isinstance(value, str) and value else default


def _inventory_root(payload: dict[str, Any]) -> dict[str, Any]:
    inventory = payload.get("inventory")
    if isinstance(inventory, dict):
        return inventory
    return payload


def load_inventory(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise SystemExit(f"Missing find-skills inventory `{path}`.")
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise SystemExit(f"Inventory `{path}` must be a JSON object.")
    return _inventory_root(payload)


def summarize_inventory(inventory: dict[str, Any]) -> dict[str, Any]:
    sections: list[dict[str, Any]] = []
    total_items = 0
    layer_counts: Counter[str] = Counter()
    source_counts: Counter[str] = Counter()
    boundary_counts: Counter[str] = Counter()

    for key, title in SECTION_SPECS:
        raw_items = [item for item in _as_list(inventory.get(key)) if isinstance(item, dict)]
        items: list[dict[str, Any]] = []
        for item in raw_items:
            access_modes = _strings(item.get("access_modes"))
            recommendation_role = _text(item.get("recommendation_role"), default="-")
            supports_public_skills = _strings(item.get("supports_public_skills"))
            layer = _text(item.get("layer"), default=title.lower())
            source = _text(item.get("source"), default="-")
            kind = _text(item.get("kind"), default="-")
            boundary = boundary_label(
                section_key=key,
                source=source,
                kind=kind,
                recommendation_role=recommendation_role,
            )
            normalized = {
                "id": _text(item.get("id"), default=_text(item.get("tool_id"), default="-")),
                "layer": layer,
                "source": source,
                "kind": kind,
                "boundary": boundary,
                "access_modes": access_modes,
                "supports_public_skills": supports_public_skills,
                "recommendation_role": recommendation_role,
                "summary": _text(item.get("summary"), default=_text(item.get("description"), default="")),
            }
            items.append(normalized)
            layer_counts[layer] += 1
            source_counts[source] += 1
            boundary_counts[boundary] += 1

        total_items += len(items)
        sections.append({"key": key, "title": title, "items": sorted(items, key=lambda entry: entry["id"])})

    return {
        "sections": sections,
        "totals": {
            "items": total_items,
            "layers": dict(sorted(layer_counts.items())),
            "sources": dict(sorted(source_counts.items())),
            "boundaries": dict(sorted(boundary_counts.items())),
        },
    }


def boundary_label(*, section_key: str, source: str, kind: str, recommendation_role: str) -> str:
    if section_key == "public_skills":
        return "workflow/native"
    if section_key == "support_capabilities":
        return "runtime/native"
    if "synced" in source or "upstream" in source:
        return "tool/synced-external"
    if kind.startswith("external_"):
        role = recommendation_role if recommendation_role != "-" else "tool"
        return f"{role}/external"
    if section_key == "support_skills":
        return "tool/native"
    return "capability"


def render_markdown(summary: dict[str, Any], *, inventory_path: Path) -> str:
    today = date.today().isoformat()
    lines = [
        "# Issue 57 Capability Spectrum",
        f"Date: {today}",
        "",
        "Source: `charness-artifacts/find-skills/latest.json`.",
        "Generated by: `python3 scripts/render_issue_57_design_study.py --repo-root . --write`.",
        "",
        "This is a read-only design-study projection. It is not a source of truth,",
        "does not run live doctor checks, and does not introduce a public CLI surface.",
        "",
        "## Spectrum Summary",
        "",
        f"- inventory path: `{inventory_path.as_posix()}`",
        f"- total capability entries: `{summary['totals']['items']}`",
        f"- layer counts: {_inline_counts(summary['totals']['layers'])}",
        f"- source counts: {_inline_counts(summary['totals']['sources'])}",
        f"- boundary counts: {_inline_counts(summary['totals']['boundaries'])}",
        "",
        "## Boundary Legend",
        "",
        "- `workflow/native`: public workflow concept owned by `charness`.",
        "- `tool/native`: local support skill surface below public workflows.",
        "- `runtime/native`: local runtime capability metadata owned by `charness`.",
        "- `tool/synced-external`: materialized or upstream-consumed support surface.",
        "- `runtime/external` or `validation/external`: external integration boundary.",
        "",
        "## Access Legend",
        "",
        "- `grant`: a host-provided capability may satisfy the boundary.",
        "- `binary`: a local executable or tool runtime is involved.",
        "- `env`: environment-backed configuration or credentials may be required.",
        "- `public`: public unauthenticated access can be enough for some paths.",
        "- `human-only`: an operator step may still be required.",
        "- `degraded`: the workflow has an honest fallback or must stop short of a full claim.",
        "",
        "## Readiness Threshold Examples",
        "",
        "These examples are sanitized and explanatory only. They do not report current",
        "machine state and do not include raw `doctor` output, local paths, accounts,",
        "stdout, stderr, provenance, or tokens.",
        "",
        "| example | defined | detected | healthy | ready | degraded meaning |",
        "| --- | --- | --- | --- | --- | --- |",
        "| `gws-cli` runtime provider | integration boundary exists | `gws` binary exists | auth surface responds | auth/env readiness is satisfied | gather must stop or use a non-private fallback |",
        "| `cautilus` validation provider | validation boundary exists | `cautilus` binary exists | evaluator doctor surface responds | required support surface is materialized when needed | deterministic local gates remain authoritative |",
        "",
    ]
    for section in summary["sections"]:
        lines.extend(render_section(section))
    lines.extend(
        [
            "## Deferred From First Slice",
            "",
            "- checked-in JSON model",
            "- live doctor payload ingestion",
            "- phase barrier timeline",
            "- interactive or dashboard UI",
            "",
        ]
    )
    return "\n".join(lines)


def _inline_counts(counts: dict[str, int]) -> str:
    if not counts:
        return "`none`"
    return ", ".join(f"`{key}` `{value}`" for key, value in counts.items())


def render_section(section: dict[str, Any]) -> list[str]:
    lines = [
        f"## {section['title']}",
        "",
        "| id | boundary | layer | source | access | supports | role |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    items = section["items"]
    if not items:
        lines.append("| - | - | - | - | - | - | - |")
    for item in items:
        lines.append(
            "| "
            + " | ".join(
                [
                    _cell(item["id"]),
                    _cell(item["boundary"]),
                    _cell(item["layer"]),
                    _cell(item["source"]),
                    _cell(", ".join(item["access_modes"]) or "-"),
                    _cell(", ".join(item["supports_public_skills"]) or "-"),
                    _cell(item["recommendation_role"]),
                ]
            )
            + " |"
        )
    lines.append("")
    return lines


def _cell(value: str) -> str:
    return value.replace("|", "\\|")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    parser.add_argument("--inventory", type=Path, default=DEFAULT_INVENTORY_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--json", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = args.repo_root.resolve()
    inventory_path = args.inventory if args.inventory.is_absolute() else repo_root / args.inventory
    output_path = args.output if args.output.is_absolute() else repo_root / args.output
    inventory = load_inventory(inventory_path)
    summary = summarize_inventory(inventory)
    markdown = render_markdown(summary, inventory_path=inventory_path.relative_to(repo_root))
    payload = {
        "inventory_path": str(inventory_path.relative_to(repo_root)),
        "output_path": str(output_path.relative_to(repo_root)),
        "totals": summary["totals"],
    }
    if args.write:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(markdown, encoding="utf-8")
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
    else:
        print(markdown)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
