#!/usr/bin/env python3

from __future__ import annotations

import re
import sys
from pathlib import Path

from runtime_bootstrap import import_repo_module, load_path_module, repo_root_from_script

REPO_ROOT = repo_root_from_script(__file__)


def _resolver_path(repo_root: Path) -> Path:
    candidates = (
        repo_root / "skills" / "public" / "quality" / "scripts" / "resolve_adapter.py",
        repo_root / "skills" / "quality" / "scripts" / "resolve_adapter.py",
    )
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    raise FileNotFoundError("quality resolve_adapter.py not found")


_quality_resolve_adapter = load_path_module("quality_resolve_adapter", _resolver_path(REPO_ROOT))
load_adapter = _quality_resolve_adapter.load_adapter
_scripts_artifact_validator_module = import_repo_module(__file__, "scripts.artifact_validator")
_adapter_version_verdict = import_repo_module(__file__, "scripts.adapter_version_verdict")
_surface_contract = import_repo_module(__file__, "scripts.quality_surface_contract")
# Shared with debug through the module that owns the measurement; see its docstring
# for why dated artifacts are grandfathered.
ValidationError = _scripts_artifact_validator_module.ValidationError
add_one_pass_args = _scripts_artifact_validator_module.add_one_pass_args
add_artifact_path_arg = _scripts_artifact_validator_module.add_artifact_path_arg
resolve_artifact_override = _scripts_artifact_validator_module.resolve_artifact_override
# The canonical repo-relative renderer. A third local copy of the try/relative_to
# dance is what a duplication gate caught twice in one session.
repo_relative = import_repo_module(__file__, "scripts.core.path_portability_lib").repo_relative
find_index = _scripts_artifact_validator_module.find_index
read_lines = _scripts_artifact_validator_module.read_lines
validate_date_line = _scripts_artifact_validator_module.validate_date_line
resolve_adapter_line_budget = _scripts_artifact_validator_module.resolve_adapter_line_budget
validate_section_order = _scripts_artifact_validator_module.validate_section_order
run_validation_checks = _scripts_artifact_validator_module.run_validation_checks
_skill_ergonomics = import_repo_module(__file__, "scripts.quality_artifact_skill_ergonomics")
_skill_ergonomics_counts = _skill_ergonomics._skill_ergonomics_counts


def validate_skill_ergonomics_count_claims(lines: list[str], repo_root: Path) -> None:
    _skill_ergonomics.validate_skill_ergonomics_count_claims(
        lines, repo_root, collect_bullets=collect_bullets
    )


# The DEFAULT ceiling, in WORDS since 2026-08-19; a consuming repo raises or lowers it
# with `max_artifact_words` in its quality adapter. Both this gate and the scaffold's
# `size_budget.max_words` forecast resolve it through `resolve_adapter_line_budget`, so
# they cannot disagree. 1100 is chosen against the corpus, not converted from 140 lines:
# of 160 checked-in quality artifacts the 140-line cap admitted 153, and those ranged 229
# to 1727 words -- a 7.5x spread, so no word number reproduces the old bar. 1100 sits
# just above the corpus p90 of 997 and admits 150 of the 160; the ten it does not are
# grandfathered as dated records. (An earlier version of this comment said `admits 157 of
# the 161`. 157 was an AGREEMENT count -- how often the word verdict matched the line
# verdict -- reported as an admission count, and 161 counted the `latest.md` symlink as a
# second artifact. A bounded reviewer caught the contradiction against the `ten above
# 1100` figure two files away.)
MAX_ARTIFACT_WORDS = 1100
WORD_BUDGET_FIELD = "max_artifact_words"
REQUIRED_SECTIONS = (
    "## Scope",
    "## Surface Contract Review",
    "## Current Gates",
    "## Runtime Signals",
    "## Healthy",
    "## Weak",
    "## Missing",
    "## Deferred",
    "## Advisory",
    "## Delegated Review",
    "## Commands Run",
    "## Recommended Next Quality Moves",
    "## History",
)
LEGACY_RECOMMENDED_SECTION = "## Recommended Next Gates"
RECOMMENDED_SECTION = "## Recommended Next Quality Moves"
HISTORY_LINK_RE = re.compile(r"\[.+\]\((?:\./)?history/[^)]+\.md\)")
RUNTIME_SIGNAL_PREFIXES = (
    "- runtime source:",
    "- runtime hot spots:",
    "- coverage gate:",
    "- evaluator depth:",
)
RUNTIME_TIMING_RE = re.compile(r"\b\d+(?:\.\d+)?\s*(?:ms|s)\b")
STRUCTURED_RUNTIME_SOURCE_MARKERS = (
    ".charness/quality/runtime-signals.json",
    "scripts/record_quality_runtime.py",
    "render_runtime_summary.py",
    "check_runtime_budget.py",
)
GENERIC_STRUCTURED_RUNTIME_RE = re.compile(
    r"\bstructured\b.*\b(?:jsonl?|ya?ml|metrics?|runner output|timing capture)\b"
)
RUNTIME_SUMMARY_RENDER_MARKERS = (
    "rendered by",
    "summarized by",
    "generated by",
)
MISSING_RUNTIME_SOURCE_MARKERS = (
    "not configured",
    "no samples",
    "missing",
    "unavailable",
)
RECOMMENDED_MOVE_PREFIXES = ("- active ", "- passive ")
FORBIDDEN_SUBAGENT_BLOCKER_PHRASES = (
    "did not explicitly allow subagents",
    "explicit subagent allowance",
    "same-agent fallback",
    "same agent fallback",
    "same-agent pass as equivalent",
)
HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)
DELEGATED_REVIEW_STATUSES = ("executed", "blocked", "not_applicable")
FORBIDDEN_DELEGATED_REVIEW_STATUSES = ("missed", "not run", "not executed")
# An `executed` delegated review must substantiate itself: name the review channel
# that ran, or the disposition it came back with. A bare `- status: executed.` and a
# section whose only other content is the standing slow-gate lens bullet both fail
# this, which is the S11 stub the 2026-07-28 triage sweep reproduced.
EXECUTED_DELEGATED_REVIEW_SUBSTANTIATION = (
    "reviewer",
    "subagent",
    "sub-agent",
    "fresh-eye",
    "fresh eye",
    "bounded",
    "delegated to",
    "counterweight",
    "critique",
    "audit",
    "angle",
    "review round",
    "found",
    "finding",
    "verdict",
    "confirmed",
    "refuted",
    "refutation",
    "blocker",
    "revise",
    "sound",
    "challenged",
    "corrected",
    "inspected",
    "reviewed the",
    "returned",
    "fingerprint",
)
# A marker that the section itself negates is not substantiation: `executed (no
# reviewer, no findings)` names the vocabulary while denying every word of it.
NEGATED_MARKER_RE = re.compile(
    r"\bno\s+(?:[\w-]+\s+){0,2}?(?:"
    + "|".join(re.escape(marker) for marker in EXECUTED_DELEGATED_REVIEW_SUBSTANTIATION)
    + r")"
)
# Language-neutral alternative to the vocabulary above: a section that cites the
# review record itself (a backticked file path or a markdown link to one) has
# substantiated the claim without writing an English review noun. The validator ships
# to consuming repos whose adapter `language:` is not English, and every marker above
# is English. It requires a path SHAPE — a slash and an extension — so that filler
# like `n/a` or `and/or` does not clear the arm; it does NOT check that the file
# exists, and nothing cross-checks the cited record against the claim.
DELEGATED_REVIEW_EVIDENCE_REFERENCE_RES = (
    re.compile(r"`[^`\s]+/[^`\s]*\.[A-Za-z0-9]+`"),
    re.compile(r"\[[^\]]+\]\([^)\s]+/[^)\s]*\.[A-Za-z0-9]+\)"),
)
# Clauses that assert no review EVENT happened. These are refused under an `executed`
# status for the same reason `missed` is: the section contradicts its own verdict.
# Anchored on the verb, with modifiers allowed between `no` and the noun, because
# adjacency alone cannot tell a denied event from a negative RESULT of one: real
# checked-in artifacts write "no reviewer identified a blocker", "no reviewer saw the
# post-fix tree", and "no reviewer-attributable worktree change", and all three must
# stay legal. Denials the author phrases some other way are not caught here — the
# substantiation arm below is what a vague stub still has to clear.
_NO_REVIEWER = r"\bno (?:[\w-]+ ){0,3}(?:reviewers?|sub-?agents?)"
_NO_REVIEW_VERBS = (
    r"(?:ran|was run|were run|was spawned|were spawned|was found|were found|was available"
    r"|were available|executed|existed|participated|reviewed)"
)
EXECUTED_DELEGATED_REVIEW_CONTRADICTION_RES = tuple(
    re.compile(pattern)
    for pattern in (
        r"\bnothing (?:ran|was run|executed)\b",
        r"\bno (?:delegated )?reviews? (?:ran|was run|were run|executed|happened|occurred)\b",
        _NO_REVIEWER + r"\s+" + _NO_REVIEW_VERBS + r"\b",
        _NO_REVIEWER + r"\s+(?:was|were|could)\s+(?:not|never)\b",
        r"\b(?:nobody|no one|no-one) reviewed\b",
        r"\bwas not (?:actually )?reviewed\b",
        r"\bnever (?:ran|reviewed|executed)\b",
    )
)
SLOW_GATE_DELEGATED_LENSES = (
    "fixture-economics",
    "parallel-critical-path",
    "duplicated-proof",
)
ADVISORY_EVIDENCE_MARKERS = (
    "`",
    "inventory",
    "command:",
    "artifact:",
    "evidence:",
    "because",
    "from ",
    "found by ",
)
QUALITY_RECORD_FILENAME_DATE_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})-")
QUALITY_BODY_DATE_RE = re.compile(r"^Date:\s*(\d{4}-\d{2}-\d{2})\b")
CURRENT_POINTER_FILENAME = "latest.md"
# One measured exception, keyed by exact repo-relative path AND by the exact pair of
# dates measured on it — `(filename date, body date)`. The pair is what keeps this from
# turning the named file into a permanently overwritable slot: a SECOND overwrite of
# that same record would carry a third date and still red. It is NOT an honest
# past-midnight write: that path at revision 05608dd16 is a `Date: 2026-06-25` review
# of `inventory_skill_ergonomics.py` summary output, and commit c6b934f2c replaced the
# whole body with a different 2026-06-26 review of runtime-hotspot ranking and
# prompt-bulk inventory. (Cited as a revision rather than as a VCS command line on
# purpose: `inventory_boundary_bypass_lib.has_internal_boundary` scores this file's
# TEXT, so a command literal in a comment reads as this validator shelling out
# internally and changes the live test-boundary inventory for tests that only spawn
# it.) It is the same overwrite this rule refuses, found by the same
# signal, seven weeks before this rule existed — the displaced 06-25 record is
# recoverable and should be refiled under its own dated path, at which point this entry
# is deleted rather than kept.
DATE_COHERENCE_GRANDFATHERED = {
    "charness-artifacts/quality/2026-06-25-skill-ergonomics-yaml-summary-quality-review.md": (
        "2026-06-25",
        "2026-06-26",
    ),
}


def validate_history_section(lines: list[str]) -> None:
    start = find_index(lines, "## History") + 1
    section_lines = [line.strip() for line in lines[start:] if line.strip()]
    if not section_lines:
        raise ValidationError("`## History` must link to at least one archived review")
    if not any(HISTORY_LINK_RE.search(line) for line in section_lines):
        raise ValidationError("`## History` must contain at least one `history/*.md` markdown link")


def collect_bullets(lines: list[str]) -> list[str]:
    bullets: list[str] = []
    current: list[str] = []
    for raw in lines:
        stripped = raw.strip()
        if stripped.startswith("- "):
            if current:
                bullets.append(" ".join(current))
            current = [stripped]
            continue
        if current and (raw.startswith("  ") or not stripped):
            if stripped:
                current.append(stripped)
            continue
        if current:
            bullets.append(" ".join(current))
            current = []
    if current:
        bullets.append(" ".join(current))
    return bullets


def validate_runtime_signals_section(lines: list[str]) -> None:
    start = find_index(lines, "## Runtime Signals") + 1
    end = find_index(lines, "## Healthy")
    section_lines = collect_bullets(lines[start:end])
    missing = [
        prefix
        for prefix in RUNTIME_SIGNAL_PREFIXES
        if not any(line.startswith(prefix) for line in section_lines)
    ]
    if missing:
        raise ValidationError(
            "`## Runtime Signals` must explicitly state runtime hot spots, coverage-gate status, "
            "runtime metric source, and evaluator depth"
        )
    source_line = next(line for line in section_lines if line.startswith("- runtime source:"))
    hot_spots_line = next(line for line in section_lines if line.startswith("- runtime hot spots:"))
    source_lowered = source_line.lower()
    has_structured_source = any(
        marker in source_line for marker in STRUCTURED_RUNTIME_SOURCE_MARKERS
    ) or bool(GENERIC_STRUCTURED_RUNTIME_RE.search(source_lowered))
    has_missing_source = any(marker in source_lowered for marker in MISSING_RUNTIME_SOURCE_MARKERS)
    if (
        "`latest.md`" in source_line
        or "manual" in source_lowered
        or "hand-edited" in source_lowered
    ):
        raise ValidationError("runtime source must not be markdown or hand-edited prose")
    if not has_structured_source and not has_missing_source:
        raise ValidationError(
            "`- runtime source:` must cite structured runtime metrics or state that timing capture is missing"
        )
    if has_missing_source and RUNTIME_TIMING_RE.search(hot_spots_line):
        raise ValidationError("runtime hot spot timings require a structured runtime source")
    if RUNTIME_TIMING_RE.search(hot_spots_line) and not any(
        marker in source_lowered for marker in RUNTIME_SUMMARY_RENDER_MARKERS
    ):
        raise ValidationError(
            "runtime hot spot timings must cite the summary helper that rendered them"
        )


def normalized_recommended_heading_lines(lines: list[str]) -> list[str]:
    return [RECOMMENDED_SECTION if line == LEGACY_RECOMMENDED_SECTION else line for line in lines]


def validate_recommended_next_moves_section(lines: list[str]) -> None:
    normalized_lines = normalized_recommended_heading_lines(lines)
    start = find_index(normalized_lines, RECOMMENDED_SECTION) + 1
    end = find_index(lines, "## History")
    section_lines = [line.strip() for line in normalized_lines[start:end] if line.strip()]
    bullets = [line for line in section_lines if line.startswith("- ")]
    if not bullets:
        raise ValidationError(
            "`## Recommended Next Quality Moves` must contain at least one bullet"
        )
    if any(not line.startswith(RECOMMENDED_MOVE_PREFIXES) for line in bullets):
        raise ValidationError(
            "recommended next quality moves must start with `- active ` or `- passive `"
        )
    for line in bullets:
        if line.startswith("- passive ") and " because" not in line and " until" not in line:
            raise ValidationError(
                "passive recommended next quality moves must explain why they are passive"
            )


def validate_advisory_section(lines: list[str]) -> None:
    start = find_index(lines, "## Advisory") + 1
    end = find_index(lines, "## Delegated Review")
    section_lines = [line.strip() for line in lines[start:end] if line.strip()]
    bullets = [line for line in section_lines if line.startswith("- ")]
    if not bullets:
        raise ValidationError("`## Advisory` must contain at least one bullet")
    lowered = "\n".join(section_lines).lower()
    if "none" in lowered and "none found by inventory" not in lowered:
        raise ValidationError(
            "empty advisory claims must use `none found by inventory` evidence wording"
        )
    if "none found by inventory" in lowered and not any(
        token in lowered for token in ("command:", "artifact:", "`")
    ):
        raise ValidationError(
            "empty advisory claims must cite inventory-backed command or artifact evidence"
        )
    for bullet in bullets:
        bullet_lowered = bullet.lower()
        if "none found by inventory" in bullet_lowered:
            continue
        if not any(marker in bullet_lowered for marker in ADVISORY_EVIDENCE_MARKERS):
            raise ValidationError(
                "advisory bullets must cite inventory, command, artifact, or other explicit evidence"
            )


def strip_html_comments(lines: list[str]) -> list[str]:
    """Drop `<!-- ... -->` fill-guard text before reading a section as author claims.

    Authoring guidance planted in the template is not the author's own assertion; the
    repo has already confirmed that class (quoted text read as an assertion). Left in,
    the `## Delegated Review` fill guard both trips the contradiction arm and satisfies
    the substantiation arm all by itself.

    Substitution runs over the JOINED text, not line by line, so a guard an author or a
    formatter wrapped across lines is still stripped. Callers apply this per rule rather
    than to the whole artifact on purpose: `<!-- reproduction-source -->` on the runtime
    source line is a machine marker other checkers consume, and must survive.
    """
    return [
        line.strip()
        for line in HTML_COMMENT_RE.sub("", "\n".join(lines)).splitlines()
        if line.strip()
    ]


def declared_delegated_review_status(section_lines: list[str]) -> str | None:
    """Return the status the section actually declares, not any status word it mentions.

    The first status-bearing line wins, and within it the earliest status token wins, so
    `not_applicable — TODO record executed with the reviewer verdict` (the scaffold's own
    unfilled slot) reads as `not_applicable` rather than arming the executed floor.
    """
    for line in section_lines:
        lowered = line.lower()
        hits = [
            (lowered.index(status), status)
            for status in DELEGATED_REVIEW_STATUSES
            if status in lowered
        ]
        if hits:
            return min(hits)[1]
    return None


def validate_executed_delegated_review_substance(section_lines: list[str]) -> None:
    # floor-addition-restraint: added as a blocking floor because the fail-open was
    # MEASURED, not imagined — sweep row S11 reproduced `- status: executed` certifying
    # a review that named nothing that ran, on the section whose whole job is to
    # disclose whether a different agent context read the work. Restraint applied:
    # substantiation stays a disclosure floor (name the channel, the disposition, or
    # the record's path), not a shape the author must learn a new label for, and it is
    # measured against every checked-in executed section (71 of 71 pass).
    section_text = "\n".join(section_lines)
    lowered = section_text.lower()
    contradiction = next(
        (regex for regex in EXECUTED_DELEGATED_REVIEW_CONTRADICTION_RES if regex.search(lowered)),
        None,
    )
    if contradiction is not None:
        raise ValidationError(
            "executed delegated review must not also state that no review ran; report blocked with a "
            "concrete host/tool signal, or not_applicable with a reason"
        )
    unnegated = NEGATED_MARKER_RE.sub(" ", lowered)
    if any(marker in unnegated for marker in EXECUTED_DELEGATED_REVIEW_SUBSTANTIATION):
        return
    if any(regex.search(section_text) for regex in DELEGATED_REVIEW_EVIDENCE_REFERENCE_RES):
        return
    raise ValidationError(
        "executed delegated review must name the review channel that ran (reviewer, bounded "
        "subagent, critique angle, counterweight), the disposition it returned (findings, "
        "verdict, what it confirmed or refuted), or cite the review record's path"
    )


def validate_delegated_review_section(lines: list[str]) -> None:
    start = find_index(lines, "## Delegated Review") + 1
    end = find_index(lines, "## Commands Run")
    section_lines = strip_html_comments(lines[start:end])
    if not section_lines:
        raise ValidationError(
            "`## Delegated Review` must record executed, blocked, or not_applicable status"
        )
    lowered = "\n".join(section_lines).lower()
    # A forbidden status is refused wherever it appears, comment or not: stripping
    # guidance must never buy back a "not run" the author wrote down.
    raw_lowered = "\n".join(lines[start:end]).lower()
    if any(status in raw_lowered for status in FORBIDDEN_DELEGATED_REVIEW_STATUSES):
        raise ValidationError(
            "`## Delegated Review` must not report a missed review; use executed, blocked with a concrete "
            "host/tool signal, or not_applicable with a reason"
        )
    if not any(status in lowered for status in DELEGATED_REVIEW_STATUSES):
        raise ValidationError(
            "`## Delegated Review` must include executed, blocked, or not_applicable status"
        )
    # Trigger on the authored claim, but let the signal itself satisfy it from anywhere
    # in the section, so a host signal written inside a comment still counts.
    # `delegation signal:` is the third accepted heading. A user who DECLINES the
    # standing delegation request is a real, recorded reason the review did not
    # run, but it is not a host or tool signal — and without this the only way to
    # satisfy the floor was to write a `host signal:` line that would be a lie.
    # Sibling of the same widening in `validate_critique_artifacts.SIGNAL_HEADINGS`;
    # widening what this floor ACCEPTS refuses strictly less.
    if (
        "blocked" in lowered
        and "host signal:" not in raw_lowered
        and "tool signal:" not in raw_lowered
        and "delegation signal:" not in raw_lowered
    ):
        raise ValidationError(
            "blocked delegated review must cite a concrete host signal, tool signal, or delegation signal"
        )
    if declared_delegated_review_status(section_lines) == "executed":
        validate_executed_delegated_review_substance(section_lines)
    # Comments stripped here too: the scaffold's own delegated-review guard mentions
    # slow-gate lenses, and unstripped it scoped every scaffolded artifact as a
    # runtime review that must name all three.
    artifact_text = "\n".join(strip_html_comments(lines)).lower()
    slow_gate_scope = any(
        token in artifact_text for token in ("slow", "standing test", "fixture economics")
    )
    if slow_gate_scope and "executed" in lowered:
        missing = [lens for lens in SLOW_GATE_DELEGATED_LENSES if lens not in lowered]
        if missing:
            raise ValidationError(
                "runtime/test quality artifacts with executed delegated review must name slow-gate lenses: "
                + ", ".join(missing)
            )


def validate_subagent_blocker_reasoning(lines: list[str]) -> None:
    for raw in lines:
        lowered = raw.lower()
        for phrase in FORBIDDEN_SUBAGENT_BLOCKER_PHRASES:
            if phrase in lowered:
                raise ValidationError(
                    "quality artifact must not treat missing explicit subagent allowance as the canonical blocker; "
                    "cite a concrete host signal or describe the pass as degraded/unprobed"
                )


# The `Date:` header value, read from the PREAMBLE only: the scan stops at the first
# `## ` heading so a body line that happens to start with `Date:` can never become the
# artifact's date channel.
def preamble_date(lines: list[str]) -> str | None:
    preamble_end = next(
        (index for index, raw in enumerate(lines) if raw.strip().startswith("## ")), len(lines)
    )
    matched = (QUALITY_BODY_DATE_RE.match(raw.strip()) for raw in lines[:preamble_end])
    return next((match.group(1) for match in matched if match), None)


def validate_date_channel_coherence(path: Path, lines: list[str], repo_root: Path) -> None:
    """Refuse a quality record whose `Date:` header disagrees with its own filename."""
    # In THIS family that disagreement is not a dating nuance — it is the fingerprint of
    # a lost record. #620: `scaffold_quality_artifact.py` writes a FRESH `date_text` into the STALE
    # path `scaffold_artifact_lib.current_pointer_write_path` hands back — the current
    # pointer's TARGET, i.e. the PREVIOUS review's dated file. A new review therefore
    # lands on top of an old one with no rename, no collision, and no error; the only
    # thing left on disk pointing at the loss is the body date no longer matching the
    # filename date. That is exactly what happened: the 2026-08-14 current-contract
    # cleanup review overwrote the 2026-08-13 issue-616 lifecycle record in place, and
    # the next review's `## History` then linked one review's TITLE to the other
    # review's FILE. `write_target_facts` already reports `overwrite_existing_content`
    # and says of itself that it is "a FACT, not a policy"; nothing consumed it. The
    # skill prose warned at length. The prose is what failed, so the teeth go here.
    #
    # Deliberately NOT a +/-1 day tolerance. The #620 instance is itself exactly +1
    # day (filename 2026-08-13, body 2026-08-14), because a review written after the
    # previous day's pointer is the ordinary way this happens — a tolerance would be a
    # hole shaped like the reported defect.
    #
    # `critique_enforcement_scope.date_channel_disagreement` computes the same signal
    # and deliberately only REPORTS it. That disposition does NOT transfer, and
    # re-deriving it here would reproduce #620: it rests on `critique_observed_date`
    # taking `max(body, filename)`, so on the critique surface a disagreement already
    # buys the artifact no grandfather and failing would cost a real artifact to close
    # a hole that is already closed. The quality family has no such `max()` and no hole
    # to be already-closed — a disagreement here means content was destroyed.
    #
    # A symlinked current pointer is followed, not exempted: `run-quality.sh` validates
    # the adapter default `charness-artifacts/quality/latest.md`, which is the very
    # channel #620 was written through, so reading the LINK's name would exempt the
    # repo's own gate run from the rule. A `latest.md` that is a real file is a
    # different object — a pointer whose body is a copy of the record it stands for
    # (`charness-artifacts/quality/sloc-inventory/latest.md` carries `Date: 2026-05-04`
    # by design) — and stays exempt. A filename with no date prefix has no second
    # channel to disagree with and is exempt too.
    filename = path.resolve().name if path.is_symlink() else path.name
    if filename == CURRENT_POINTER_FILENAME:
        return
    named = QUALITY_RECORD_FILENAME_DATE_RE.match(filename)
    recorded = preamble_date(lines)
    if named is None or recorded is None or recorded == named.group(1):
        return
    relative = repo_relative(repo_root, path)
    if DATE_COHERENCE_GRANDFATHERED.get(relative) == (named.group(1), recorded):
        return
    raise ValidationError(
        f"quality record `{relative}` says `Date: {recorded}` but its filename is dated "
        f"{named.group(1)}: a dated record was overwritten in place. Write the new review to its own "
        f"dated path (`resolve_quality_artifact.py --intent record`) and restore the displaced record."
    )


def validate_surface_contract(lines: list[str]) -> None:
    try:
        _surface_contract.validate_surface_contract_section(lines)
    except _surface_contract.SurfaceContractError as exc:
        raise ValidationError(str(exc)) from exc


def validate_quality_artifact(
    path: Path, *, repo_root: Path | None = None, collect_all: bool = False
) -> None:
    lines = read_lines(path)
    resolved_repo_root = repo_root or REPO_ROOT

    def _header() -> None:
        if not lines or lines[0].strip() != "# Quality Review":
            raise ValidationError("quality artifact must start with `# Quality Review`")

    checks = (
        _header,
        # Grandfathered on the unit change; `word_ceiling_enforced` owns why. Latent
        # rather than live here (this gate takes ONE artifact, not a corpus), but ten
        # checked-in artifacts sit above 1100. Found by a bounded review, not a gate.
        lambda: _scripts_artifact_validator_module.validate_max_words_when_dated_in_scope(
            path,
            lines,
            max_words=resolve_adapter_line_budget(
                load_adapter,
                resolved_repo_root,
                field=WORD_BUDGET_FIELD,
                default=MAX_ARTIFACT_WORDS,
            ),
            artifact_label="quality artifact",
            artifact_type="quality",
        ),
        lambda: validate_date_line(lines),
        lambda: validate_date_channel_coherence(path, lines, resolved_repo_root),
        lambda: validate_section_order(
            normalized_recommended_heading_lines(lines), REQUIRED_SECTIONS
        ),
        lambda: validate_surface_contract(lines),
        lambda: validate_runtime_signals_section(lines),
        lambda: validate_advisory_section(lines),
        lambda: validate_delegated_review_section(lines),
        lambda: validate_recommended_next_moves_section(lines),
        lambda: validate_history_section(lines),
        lambda: validate_subagent_blocker_reasoning(lines),
        lambda: validate_skill_ergonomics_count_claims(lines, resolved_repo_root),
    )

    # collect_all surfaces every violation in one pass (the CLI default) so a
    # multi-rule draft is fixed in a single edit pass instead of one rule per
    # gate run — the closeout-churn fix; --fail-fast opts back into stopping at
    # the first violation.
    run_validation_checks(checks, collect_all=collect_all, artifact_label="quality artifact")


def main() -> int:
    args = _scripts_artifact_validator_module.parse_single_artifact_validator_args(
        surface="quality", default_repo_root=REPO_ROOT
    )

    repo_root = args.repo_root.resolve()
    # Before resolving the artifact path or the line ceiling: on a version this reader
    # cannot speak, both come from charness defaults rather than from what the repo
    # declared, so the run would validate a file at a path the repo never named and
    # enforce a ceiling it never chose.
    refused = _adapter_version_verdict.refuse_unspeakable_version(
        load_adapter, repo_root, adapter_name="quality-adapter.yaml"
    )
    if refused is not None:
        return refused
    adapter = load_adapter(repo_root)
    artifact_path = resolve_artifact_override(args, repo_root, adapter["artifact_path"])
    validate_quality_artifact(artifact_path, repo_root=repo_root, collect_all=not args.fail_fast)
    print(f"Validated quality artifact {repo_relative(repo_root, artifact_path)}.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except ValidationError as exc:
        print(str(exc), file=sys.stderr)
        sys.exit(1)
