#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from runtime_bootstrap import import_repo_module, load_path_module, repo_root_from_script

REPO_ROOT = repo_root_from_script(__file__)


def _resolver_path(repo_root: Path) -> Path:
    candidates = (
        repo_root / "skills" / "public" / "quality" / "scripts" / "resolve_adapter.py",
        repo_root / "skills" / "quality" / "scripts" / "resolve_adapter.py",
    )
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    raise FileNotFoundError("quality resolve_adapter.py not found")


_quality_resolve_adapter = load_path_module("quality_resolve_adapter", _resolver_path(REPO_ROOT))
load_adapter = _quality_resolve_adapter.load_adapter
_scripts_artifact_validator_module = import_repo_module(__file__, "scripts.artifact_validator")
_skill_markdown_lib = import_repo_module(__file__, "scripts.skill_markdown_lib")
ValidationError = _scripts_artifact_validator_module.ValidationError
find_index = _scripts_artifact_validator_module.find_index
read_lines = _scripts_artifact_validator_module.read_lines
validate_date_line = _scripts_artifact_validator_module.validate_date_line
validate_max_lines = _scripts_artifact_validator_module.validate_max_lines
validate_section_order = _scripts_artifact_validator_module.validate_section_order
run_validation_checks = _scripts_artifact_validator_module.run_validation_checks

MAX_ARTIFACT_LINES = 140
REQUIRED_SECTIONS = (
    "## Scope",
    "## Current Gates",
    "## Runtime Signals",
    "## Healthy",
    "## Weak",
    "## Missing",
    "## Deferred",
    "## Advisory",
    "## Delegated Review",
    "## Commands Run",
    "## Recommended Next Quality Moves",
    "## History",
)
LEGACY_RECOMMENDED_SECTION = "## Recommended Next Gates"
RECOMMENDED_SECTION = "## Recommended Next Quality Moves"
HISTORY_LINK_RE = re.compile(r"\[.+\]\((?:\./)?history/[^)]+\.md\)")
RUNTIME_SIGNAL_PREFIXES = (
    "- runtime source:",
    "- runtime hot spots:",
    "- coverage gate:",
    "- evaluator depth:",
)
RUNTIME_TIMING_RE = re.compile(r"\b\d+(?:\.\d+)?\s*(?:ms|s)\b")
STRUCTURED_RUNTIME_SOURCE_MARKERS = (
    ".charness/quality/runtime-signals.json",
    "scripts/record_quality_runtime.py",
    "render_runtime_summary.py",
    "check_runtime_budget.py",
)
GENERIC_STRUCTURED_RUNTIME_RE = re.compile(
    r"\bstructured\b.*\b(?:jsonl?|ya?ml|metrics?|runner output|timing capture)\b"
)
RUNTIME_SUMMARY_RENDER_MARKERS = (
    "rendered by",
    "summarized by",
    "generated by",
)
MISSING_RUNTIME_SOURCE_MARKERS = (
    "not configured",
    "no samples",
    "missing",
    "unavailable",
)
RECOMMENDED_MOVE_PREFIXES = ("- active ", "- passive ")
FORBIDDEN_SUBAGENT_BLOCKER_PHRASES = (
    "did not explicitly allow subagents",
    "explicit subagent allowance",
    "same-agent fallback",
    "same agent fallback",
    "same-agent pass as equivalent",
)
DELEGATED_REVIEW_STATUSES = ("executed", "blocked", "not_applicable")
FORBIDDEN_DELEGATED_REVIEW_STATUSES = ("missed", "not run", "not executed")
SLOW_GATE_DELEGATED_LENSES = (
    "fixture-economics",
    "parallel-critical-path",
    "duplicated-proof",
)
ADVISORY_EVIDENCE_MARKERS = (
    "`",
    "inventory",
    "command:",
    "artifact:",
    "evidence:",
    "because",
    "from ",
    "found by ",
)
SKILL_ERGONOMICS_COUNT_RE = re.compile(
    r"`?core_nonempty_lines=(?P<core>\d+)`?.{0,120}?"
    r"`?reference_file_count=(?P<refs>\d+)`?.{0,120}?"
    r"`?script_file_count=(?P<scripts>\d+)`?",
    re.DOTALL,
)
BACKTICKED_TOKEN_RE = re.compile(r"`([a-z0-9-]+)`")
PRESSURE_EXEMPT_H2_SECTIONS = {"Load-Bearing Anchors", "References"}


def validate_history_section(lines: list[str]) -> None:
    start = find_index(lines, "## History") + 1
    section_lines = [line.strip() for line in lines[start:] if line.strip()]
    if not section_lines:
        raise ValidationError("`## History` must link to at least one archived review")
    if not any(HISTORY_LINK_RE.search(line) for line in section_lines):
        raise ValidationError("`## History` must contain at least one `history/*.md` markdown link")


def collect_bullets(lines: list[str]) -> list[str]:
    bullets: list[str] = []
    current: list[str] = []
    for raw in lines:
        stripped = raw.strip()
        if stripped.startswith("- "):
            if current:
                bullets.append(" ".join(current))
            current = [stripped]
            continue
        if current and (raw.startswith("  ") or not stripped):
            if stripped:
                current.append(stripped)
            continue
        if current:
            bullets.append(" ".join(current))
            current = []
    if current:
        bullets.append(" ".join(current))
    return bullets


def validate_runtime_signals_section(lines: list[str]) -> None:
    start = find_index(lines, "## Runtime Signals") + 1
    end = find_index(lines, "## Healthy")
    section_lines = collect_bullets(lines[start:end])
    missing = [prefix for prefix in RUNTIME_SIGNAL_PREFIXES if not any(line.startswith(prefix) for line in section_lines)]
    if missing:
        raise ValidationError(
            "`## Runtime Signals` must explicitly state runtime hot spots, coverage-gate status, "
            "runtime metric source, and evaluator depth"
        )
    source_line = next(line for line in section_lines if line.startswith("- runtime source:"))
    hot_spots_line = next(line for line in section_lines if line.startswith("- runtime hot spots:"))
    source_lowered = source_line.lower()
    has_structured_source = any(marker in source_line for marker in STRUCTURED_RUNTIME_SOURCE_MARKERS) or bool(
        GENERIC_STRUCTURED_RUNTIME_RE.search(source_lowered)
    )
    has_missing_source = any(marker in source_lowered for marker in MISSING_RUNTIME_SOURCE_MARKERS)
    if "`latest.md`" in source_line or "manual" in source_lowered or "hand-edited" in source_lowered:
        raise ValidationError("runtime source must not be markdown or hand-edited prose")
    if not has_structured_source and not has_missing_source:
        raise ValidationError(
            "`- runtime source:` must cite structured runtime metrics or state that timing capture is missing"
        )
    if has_missing_source and RUNTIME_TIMING_RE.search(hot_spots_line):
        raise ValidationError("runtime hot spot timings require a structured runtime source")
    if RUNTIME_TIMING_RE.search(hot_spots_line) and not any(
        marker in source_lowered for marker in RUNTIME_SUMMARY_RENDER_MARKERS
    ):
        raise ValidationError("runtime hot spot timings must cite the summary helper that rendered them")


def normalized_recommended_heading_lines(lines: list[str]) -> list[str]:
    return [RECOMMENDED_SECTION if line == LEGACY_RECOMMENDED_SECTION else line for line in lines]


def validate_recommended_next_moves_section(lines: list[str]) -> None:
    normalized_lines = normalized_recommended_heading_lines(lines)
    start = find_index(normalized_lines, RECOMMENDED_SECTION) + 1
    end = find_index(lines, "## History")
    section_lines = [line.strip() for line in normalized_lines[start:end] if line.strip()]
    bullets = [line for line in section_lines if line.startswith("- ")]
    if not bullets:
        raise ValidationError("`## Recommended Next Quality Moves` must contain at least one bullet")
    if any(not line.startswith(RECOMMENDED_MOVE_PREFIXES) for line in bullets):
        raise ValidationError("recommended next quality moves must start with `- active ` or `- passive `")
    for line in bullets:
        if line.startswith("- passive ") and " because" not in line and " until" not in line:
            raise ValidationError("passive recommended next quality moves must explain why they are passive")


def validate_advisory_section(lines: list[str]) -> None:
    start = find_index(lines, "## Advisory") + 1
    end = find_index(lines, "## Delegated Review")
    section_lines = [line.strip() for line in lines[start:end] if line.strip()]
    bullets = [line for line in section_lines if line.startswith("- ")]
    if not bullets:
        raise ValidationError("`## Advisory` must contain at least one bullet")
    lowered = "\n".join(section_lines).lower()
    if "none" in lowered and "none found by inventory" not in lowered:
        raise ValidationError("empty advisory claims must use `none found by inventory` evidence wording")
    if "none found by inventory" in lowered and not any(token in lowered for token in ("command:", "artifact:", "`")):
        raise ValidationError("empty advisory claims must cite inventory-backed command or artifact evidence")
    for bullet in bullets:
        bullet_lowered = bullet.lower()
        if "none found by inventory" in bullet_lowered:
            continue
        if not any(marker in bullet_lowered for marker in ADVISORY_EVIDENCE_MARKERS):
            raise ValidationError("advisory bullets must cite inventory, command, artifact, or other explicit evidence")


def validate_delegated_review_section(lines: list[str]) -> None:
    start = find_index(lines, "## Delegated Review") + 1
    end = find_index(lines, "## Commands Run")
    section_lines = [line.strip() for line in lines[start:end] if line.strip()]
    if not section_lines:
        raise ValidationError("`## Delegated Review` must record executed, blocked, or not_applicable status")
    lowered = "\n".join(section_lines).lower()
    if any(status in lowered for status in FORBIDDEN_DELEGATED_REVIEW_STATUSES):
        raise ValidationError(
            "`## Delegated Review` must not report a missed review; use executed, blocked with a concrete "
            "host/tool signal, or not_applicable with a reason"
        )
    if not any(status in lowered for status in DELEGATED_REVIEW_STATUSES):
        raise ValidationError("`## Delegated Review` must include executed, blocked, or not_applicable status")
    if "blocked" in lowered and "host signal:" not in lowered and "tool signal:" not in lowered:
        raise ValidationError("blocked delegated review must cite a concrete host signal or tool signal")
    artifact_text = "\n".join(lines).lower()
    slow_gate_scope = any(token in artifact_text for token in ("slow", "standing test", "fixture economics"))
    if slow_gate_scope and "executed" in lowered:
        missing = [lens for lens in SLOW_GATE_DELEGATED_LENSES if lens not in lowered]
        if missing:
            raise ValidationError(
                "runtime/test quality artifacts with executed delegated review must name slow-gate lenses: "
                + ", ".join(missing)
            )


def validate_subagent_blocker_reasoning(lines: list[str]) -> None:
    for raw in lines:
        lowered = raw.lower()
        for phrase in FORBIDDEN_SUBAGENT_BLOCKER_PHRASES:
            if phrase in lowered:
                raise ValidationError(
                    "quality artifact must not treat missing explicit subagent allowance as the canonical blocker; "
                    "cite a concrete host signal or describe the pass as degraded/unprobed"
                )


def _count_files(path: Path) -> int:
    if not path.is_dir():
        return 0
    return sum(1 for candidate in path.rglob("*") if candidate.is_file())


def _skill_ergonomics_counts(repo_root: Path, skill_id: str) -> dict[str, int]:
    skill_path = repo_root / "skills" / "public" / skill_id / "SKILL.md"
    if not skill_path.is_file():
        raise ValidationError(f"quality artifact cites skill ergonomics counts for missing skill `{skill_id}`")
    skill_dir = skill_path.parent
    body_lines: list[str] = []
    active_section: str | None = None
    for raw in _skill_markdown_lib.strip_frontmatter(skill_path.read_text(encoding="utf-8")).splitlines():
        stripped = raw.strip()
        if stripped.startswith("## "):
            active_section = stripped[3:].strip()
        if active_section not in PRESSURE_EXEMPT_H2_SECTIONS:
            body_lines.append(raw)
    return {
        "core_nonempty_lines": sum(1 for line in body_lines if line.strip()),
        "reference_file_count": _count_files(skill_dir / "references"),
        "script_file_count": _count_files(skill_dir / "scripts"),
    }


def _claim_skill_id(repo_root: Path, claim_text: str) -> str:
    candidates = [
        match.group(1)
        for match in BACKTICKED_TOKEN_RE.finditer(claim_text)
        if (repo_root / "skills" / "public" / match.group(1) / "SKILL.md").is_file()
    ]
    if not candidates:
        raise ValidationError(
            "quality artifact has explicit skill ergonomics counts but no backticked public skill id "
            "in the same bullet"
        )
    return candidates[0]


def validate_skill_ergonomics_count_claims(lines: list[str], repo_root: Path) -> None:
    for claim_text in collect_bullets(lines):
        match = SKILL_ERGONOMICS_COUNT_RE.search(claim_text)
        if not match:
            continue
        skill_id = _claim_skill_id(repo_root, claim_text)
        claimed = {
            "core_nonempty_lines": int(match.group("core")),
            "reference_file_count": int(match.group("refs")),
            "script_file_count": int(match.group("scripts")),
        }
        actual = _skill_ergonomics_counts(repo_root, skill_id)
        if claimed != actual:
            raise ValidationError(
                f"quality artifact has stale skill ergonomics counts for `{skill_id}`: "
                f"claimed {claimed}, actual {actual}"
            )


def validate_quality_artifact(path: Path, *, repo_root: Path | None = None, collect_all: bool = False) -> None:
    lines = read_lines(path)
    resolved_repo_root = repo_root or REPO_ROOT

    def _header() -> None:
        if not lines or lines[0].strip() != "# Quality Review":
            raise ValidationError("quality artifact must start with `# Quality Review`")

    checks = (
        _header,
        lambda: validate_max_lines(lines, max_lines=MAX_ARTIFACT_LINES, artifact_label="quality artifact"),
        lambda: validate_date_line(lines),
        lambda: validate_section_order(normalized_recommended_heading_lines(lines), REQUIRED_SECTIONS),
        lambda: validate_runtime_signals_section(lines),
        lambda: validate_advisory_section(lines),
        lambda: validate_delegated_review_section(lines),
        lambda: validate_recommended_next_moves_section(lines),
        lambda: validate_history_section(lines),
        lambda: validate_subagent_blocker_reasoning(lines),
        lambda: validate_skill_ergonomics_count_claims(lines, resolved_repo_root),
    )

    # Default fails fast on the first violation; --report-all surfaces every
    # violation in one pass via the shared artifact_validator helper.
    run_validation_checks(checks, collect_all=collect_all, artifact_label="quality artifact")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    parser.add_argument(
        "--report-all",
        action="store_true",
        help="Report every rule violation in one pass instead of failing on the first.",
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    adapter = load_adapter(repo_root)
    artifact_path = repo_root / adapter["artifact_path"]
    validate_quality_artifact(artifact_path, repo_root=repo_root, collect_all=args.report_all)
    print(f"Validated quality artifact {artifact_path.relative_to(repo_root)}.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except ValidationError as exc:
        print(str(exc), file=sys.stderr)
        sys.exit(1)
