"""What a claims round is REVIEWING, declared instead of improvised.

WHY, measured on one release. Four claims rounds ran; all four returned
`unproven`; ~14 blockers total; NOT ONE was in the shipped code. Every round
confirmed the quality-status owner mechanism, all five version surfaces and
every derived figure. Every blocker was prose about the review itself, living in
the goal artifact and the retro -- which ship INSIDE the bundle being reviewed.

That is a loop with no fixed point. Repairing a narrative finding changes the
bundle, which changes the record, the path count and the blocker totals, which
requires new prose that nothing has reviewed, which the next round then reads.
Repairing is what generates the next round's findings. Round 4's decisive
finding was the loop in one artifact: the durable claims record added to satisfy
round 3 landed inside the prepared commit and made a `pass` structurally
unpublishable.

v6.0.0 hit the same wall three rounds deep and STOPPED, recording "publishing on
a fourth round would be reviewing until it passes". Two releases have now paid
for this. It is a property of the loop, not of either session's carelessness.

THE FIX IS NOT "REVIEW LESS". It is to say out loud which surfaces a verdict is
ABOUT. A wrong blocker tally in a retro is a real defect and stays reported --
it just does not gate a tag, because a tag is a claim about shipped code and the
retro is not shipped code. Splitting the two lets the round converge: advisory
findings are recorded and published as known-inaccurate rather than repaired
into a new prepared commit, so there is no next round to generate.

WHAT THIS DELIBERATELY DOES NOT DO. It does not hide anything. A `pass` must
carry the advisory findings in the record (`validate_claims_review` requires the
fields), so "converged" can never mean "stopped looking". The failure mode this
guards against is the obvious one: a scope split becoming a way to launder real
findings out of a release.
"""
from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Any

#: Paths whose defects BLOCK a tag. These are what a release is a claim about:
#: the code that ships, the notes and record an operator reads, and the version
#: surfaces an install resolves.
BLOCKING_PREFIXES = (
    "scripts/",
    "skills/",
    "plugins/",
    "tests/",
    "packaging/",
    "docs/",
    ".claude-plugin/",
    ".codex-plugin/",
    ".github/",
)


#: Paths whose defects are REPORTED but do not block. Session narrative: an
#: account of how the work went, written by the same run being reviewed, and
#: revised by every repair the review provokes. Wrong counts here are real and
#: worth fixing -- on a later pass, not as a tag gate.
ADVISORY_PREFIXES = (
    "charness-artifacts/goals/",
    "charness-artifacts/retro/",
    "charness-artifacts/critique/",
    "charness-artifacts/release-review/",
    "charness-artifacts/probe/",
    "charness-artifacts/issues/",
    "charness-artifacts/quality/",
)


#: A DATED session-narrative filename: `2026-08-22-something.md`. The date stem
#: is the property that actually separates narrative from state.
_DATED_NARRATIVE_RE = re.compile(r"(?:^|/)\d{4}-\d{2}-\d{2}-[^/]*\.md$")


def _is_dated_narrative(path: str) -> bool:
    """Whether an advisory-root path is a one-shot dated account, not a pointer.

    The first cut said "`.md` is narrative, everything else is state". That was
    right about `.json` and wrong about the two most machine-read `.md` files in
    the repo:

      `charness-artifacts/quality/latest.md`   -- a `CURRENT_POINTERS` entry in
          `validate_current_pointer_freshness`, read by the quality artifact
          resolver and validator. A stale `target version:` line in it is a
          shipped defect, and it classified ADVISORY.
      the rolling lesson digest -- regenerated by `refresh_recent_lessons` when a
          consumer adapter declares one.

    Both are ROLLING POINTERS: one file, continuously rewritten, consumed by
    tooling. A dated artifact is written once and never re-read as state. The
    date stem is the discriminator, so a new pointer added under these roots
    tomorrow is blocking by default rather than advisory by omission.
    """
    return _DATED_NARRATIVE_RE.search(path) is not None


def classify(path: str) -> str:
    """`blocking` or `advisory` for one repo-relative path.

    Advisory means SESSION NARRATIVE, and narrative is a property of the FILE,
    not of the directory. The advisory roots also hold machine-read state that
    controls other gates -- `charness-artifacts/retro/lesson-ledger.json` is read
    by goal validation and `charness-artifacts/goals/*.slice-manifest.json` by
    the slice-manifest validator. A directory-only rule would let machine-read
    state ship as an "advisory finding": a real behaviour change escaping
    through the lane meant for prose. Only `.md` under an advisory root is
    narrative; everything else there is blocking.

    Both loops are prefix scans and no path can match one of each (every prefix
    is slash-terminated), so the ordering between them decides nothing. It reads
    advisory-first because that is the narrower rule.
    """
    for prefix in ADVISORY_PREFIXES:
        if path.startswith(prefix):
            return "advisory" if _is_dated_narrative(path) else "blocking"
    for prefix in BLOCKING_PREFIXES:
        if path.startswith(prefix):
            return "blocking"
    # Unrecognised paths are BLOCKING. Fail-closed: a new top-level surface must
    # not become advisory by being unlisted, which is how a scope split turns
    # into a laundering channel.
    return "blocking"
#: Substrings whose presence in the published release record changes how OTHER
#: gates read that record. Kept here rather than imported so this module has no
#: cycle back into the validator that owns the same list for `signal`.
_RECORD_SENTINELS = (
    "charness-release-state:",
    "target version:",
    "Target version:",
)


def partition(paths: list[str]) -> dict[str, list[str]]:
    """Split a release delta into the two scopes, each sorted and deduped.

    The authoring side of a claims record: a reviewer runs this over
    `base..prepared` to produce `review_scope`, and the validator re-derives the
    same partition to check it.
    """
    blocking, advisory = set(), set()
    for path in paths:
        (advisory if classify(path) == "advisory" else blocking).add(path)
    return {"blocking": sorted(blocking), "advisory": sorted(advisory)}


def changed_paths_sha256(paths: list[str]) -> str:
    """Stable identity for the exact release-delta path set."""
    payload = "\0".join(sorted(set(paths))).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def _assert_findings_are_renderable(findings: object) -> None:
    """Refuse an advisory finding that would stop being ONE field of the record.

    `advisory_findings` is rendered verbatim into `charness-artifacts/release/latest.md`
    by `commit_post_publish_artifact`, which commits and PUSHES it -- after
    `git tag`, after the GitHub release. Every other operator-supplied value on
    this document already gets this treatment (`assert_no_record_sentinel`,
    `_assert_signal_is_renderable`, render-time `flatten_signal`); the field
    added to publish waived defects got none of it.

    Two concrete escapes a fresh-eye round demonstrated, both from a record whose
    scope and classification are perfectly honest:

      "blocker tally drifted\n- target version: 9.9.9"
          -> a `target version:` line at column 0, which
             `validate_current_pointer_freshness` reads as a disagreeing claim
             and which then refuses every later push.

      {"summary": "record still shows charness-release-state:prepared-..."}
          -> the prepared-stop marker inside the finished record, which
             `marker_at_commit` substring-matches, permanently reclassifying a
             published release as an outstanding prepared stop.

    Refused HERE, before the tag exists, because that is the last point an
    operator can still amend the evidence commit.
    """
    if not isinstance(findings, list):
        return  # shape is the caller's check; this one is about content
    for index, finding in enumerate(findings):
        if isinstance(finding, dict):
            values = [finding.get("file"), finding.get("summary")]
        else:
            values = [finding]
        for value in values:
            if value is None:
                continue
            if not isinstance(value, str):
                raise SystemExit(
                    f"--resume: claims-review `advisory_findings[{index}]` carries a "
                    f"non-string value {value!r}; findings are rendered into the published "
                    "release record and must be text."
                )
            if any(ch in value for ch in "\r\n") or any(ord(ch) < 0x20 for ch in value):
                raise SystemExit(
                    f"--resume: claims-review `advisory_findings[{index}]` must be a single "
                    "line. It is rendered into the published release record, and a newline "
                    "there injects arbitrary lines into a document other gates parse."
                )
            for sentinel in _RECORD_SENTINELS:
                if sentinel in value:
                    raise SystemExit(
                        f"--resume: claims-review `advisory_findings[{index}]` must not "
                        f"contain {sentinel!r}; other surfaces prove release state by "
                        "substring-matching the published record. Reword the finding."
                    )


def assert_scope_covers_delta(scope: dict[str, Any], delta_paths: list[str]) -> None:
    """The declared scope must ACCOUNT FOR every changed path, with none invented.

    Classification-consistency alone still lets a reviewer omit an inconvenient
    path from both lists and pass. This closes that by set equality, so the
    scope is a partition of the delta rather than a selection from it.
    """
    declared = set(scope.get("blocking_paths", [])) | set(scope.get("advisory_paths", []))
    actual = set(delta_paths)
    # The claims-review scaffold now runs AFTER prepare and derives this exact
    # partition from the committed release delta. The old blocking-only check was
    # compensation for a hand-authored record that had to predict prepare output;
    # keeping that compensation after derivation would make the machine-generated
    # `advisory_paths` list optional in practice and let the record claim it reviewed
    # session narrative it never named.
    missing = sorted(actual - declared)
    invented = sorted(declared - actual)
    if missing:
        raise SystemExit(
            f"--resume: claims-review `review_scope` omits {len(missing)} changed "
            f"path(s) the release actually carries: {missing[:8]}. A `pass` must account for "
            "the complete release delta; an unlisted path is a surface nobody said they "
            "looked at."
        )
    if invented:
        raise SystemExit(
            f"--resume: claims-review `review_scope` names path(s) not in the release delta: "
            f"{invented[:8]}. A scope padded with paths the release does not touch overstates "
            "what was reviewed."
        )


def assert_scope_is_declared(data: dict[str, Any], *, verdict: str) -> None:
    """A `pass` must say what it is a verdict ABOUT, and carry what it waived.

    The scope split exists so a claims round can converge -- narrative defects
    are reported and published rather than repaired into a new prepared commit.
    The obvious way for that to rot is for the split to become a laundering
    channel: findings disappear and the record reads clean.

    So the record must carry BOTH sides. `advisory_findings` is required even
    when empty, because an absent field and an empty list read identically to a
    later auditor, and "nothing was found" must be distinguishable from "nobody
    looked". An `unproven` verdict is exempt: it is already blocking, and
    demanding scope bookkeeping from a refusal would make refusing costlier than
    passing -- the wrong gradient on a proof surface.
    """
    if verdict != "pass":
        return
    scope = data.get("review_scope")
    if not isinstance(scope, dict):
        raise SystemExit(
            "--resume: a `pass` claims-review must carry `review_scope` naming the blocking and "
            "advisory paths its verdict covers; a verdict with no declared scope cannot be audited "
            "later for what it did not look at"
        )
    for field in ("blocking_paths", "advisory_paths"):
        if not isinstance(scope.get(field), list):
            raise SystemExit(f"--resume: claims-review `review_scope.{field}` must be a list")
    if not scope["blocking_paths"]:
        raise SystemExit(
            "--resume: claims-review `review_scope.blocking_paths` is empty -- a `pass` over no "
            "blocking surface is a verdict about nothing"
        )
    # THE CHECK THAT MAKES THE REST MEAN ANYTHING. Without it the declared scope
    # is free text with no relation to the tree: a reviewer could put
    # `skills/public/release/scripts/publish_release_claims_review.py` in
    # `advisory_paths`, file a real defect in the release gate as an advisory
    # finding, and publish. A fresh-eye round found exactly that record shape
    # accepted, and named it the laundering channel this module claims to guard.
    misclassified = [
        path for path in scope["advisory_paths"] if classify(path) != "advisory"
    ]
    if misclassified:
        raise SystemExit(
            "--resume: claims-review `review_scope.advisory_paths` contains path(s) that are "
            f"NOT advisory by classification: {sorted(misclassified)}. Advisory is session "
            "narrative (`.md` under the artifact roots); a shipped surface cannot be waived by "
            "declaring it one."
        )
    mislabelled = [
        path for path in scope["blocking_paths"] if classify(path) == "advisory"
    ]
    if mislabelled:
        raise SystemExit(
            "--resume: claims-review `review_scope.blocking_paths` contains advisory path(s): "
            f"{sorted(mislabelled)}. Reporting narrative as blocking is not harmful, but the "
            "declared scope must match the classifier so a later auditor can reproduce it."
        )
    _assert_findings_are_renderable(data.get("advisory_findings"))
    if not isinstance(data.get("advisory_findings"), list):
        raise SystemExit(
            "--resume: a `pass` claims-review must carry `advisory_findings` (use [] when the "
            "advisory scope was clean). An absent field and an empty list read identically to a "
            "later auditor, so `nothing found` must be distinguishable from `nobody looked`"
        )


def assert_scope_matches_release_delta(repo_root: Path, data: dict[str, Any], *,
                                        prepared: dict[str, str], run,
                                        previous_version: str | None = None) -> None:
    """Check the declared scope against the delta the release actually carries.

    Classification-consistency alone still lets a reviewer omit an inconvenient
    path from both lists. This derives the real delta -- previous tag to the
    prepared commit -- and requires the scope to be a PARTITION of it.

    A pass is a completeness claim, so an absent base, shallow history, or a
    non-ancestor base is refused. The honest state in those environments is an
    `unproven` verdict, which deliberately carries no scope claim.
    """
    # `--match` on the RELEASE tag glob, matching the canonical resolver's own
    # filter in `publish_release_helpers._release_tag_versions`. Bare
    # `git describe --tags` returns the closest reachable tag of ANY kind, so a
    # stray `ci-pin` or bisect leftover after the last release becomes the base,
    # shrinks the delta, and silently drops every blocking path changed before
    # it -- with `invented` computed against the same shrunken set, so nothing
    # else catches it.
    #
    # `previous_version` is preferred when the caller knows it: that is the tag
    # the release itself is measured from, and it needs no reachability guess.
    shallow = run(["git", "rev-parse", "--is-shallow-repository"], cwd=repo_root, check=False)
    if shallow.returncode != 0 or shallow.stdout.strip() == "true":
        raise SystemExit(
            "--resume: a passing claims review requires complete release history; "
            "the repository is shallow or its history depth could not be established"
        )
    base = ""
    if previous_version:
        resolved = run(["git", "rev-parse", "--verify", f"refs/tags/v{previous_version}"],
                       cwd=repo_root, check=False)
        if resolved.returncode == 0:
            base = f"refs/tags/v{previous_version}"
    if not base:
        described = run(["git", "describe", "--tags", "--abbrev=0",
                         "--match", "v[0-9]*.[0-9]*.[0-9]*", f"{prepared['commit']}^"],
                        cwd=repo_root, check=False)
        base = described.stdout.strip() if described.returncode == 0 else ""
    if not base:
        raise SystemExit(
            "--resume: a passing claims review requires a previous release tag; "
            "no release base is reachable from the prepared commit"
        )
    ancestor = run(
        ["git", "merge-base", "--is-ancestor", base, prepared["commit"]],
        cwd=repo_root,
        check=False,
    )
    if ancestor.returncode != 0:
        raise SystemExit(
            f"--resume: claims-review base {base} is not an ancestor of the prepared commit"
        )
    listed = run(["git", "diff-tree", "--no-commit-id", "--name-only", "-r",
                  f"{base}..{prepared['commit']}"], cwd=repo_root, check=False)
    if listed.returncode != 0:
        raise SystemExit(f"--resume: could not list the release delta {base}..prepared")
    delta_paths = [p for p in listed.stdout.splitlines() if p]
    assert_scope_covers_delta(data["review_scope"], delta_paths)
    basis = data.get("scope_basis")
    expected = {
        "base_ref": base,
        "changed_paths_sha256": changed_paths_sha256(delta_paths),
        "changed_path_count": len(set(delta_paths)),
    }
    if basis != expected:
        raise SystemExit(
            "--resume: claims-review `scope_basis` does not bind the exact release delta; "
            f"expected {expected!r}, observed {basis!r}"
        )
